// Auto-generated file

reader.ReadU16("version")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("accept_fast_explosion")
reader.ReadBool("collideable")
reader.ReadFP32("usage_distance")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "choose")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadFP32("attach_threshold")
reader.ReadFP32("attach_armor")
reader.ReadVec3("ph_box0_center")
reader.ReadVec3("ph_box0_size")
reader.ReadVec3("ph_box1_center")
reader.ReadVec3("ph_box1_size")
reader.ReadVec3("ph_box2_center")
reader.ReadVec3("ph_box2_size")
reader.ReadVec3("ph_box3_center")
reader.ReadVec3("ph_box3_size")
reader.ReadFP32("ph_autostep_height")
reader.ReadFP32("ph_jump_height")
reader.ReadFP32("ph_jumpover_depth")
reader.ReadFP32("ph_jumpover_height_min")
reader.ReadFP32("ph_jumpover_height_max")
reader.ReadFP32("ph_jumpover_use_dist")
reader.ReadFP32("ph_jumpover_time_in")
reader.ReadFP32("ph_jumpover_time_idle")
reader.ReadFP32("ph_jumpover_time_out")
reader.ReadFP32("ph_jumpover_min_reverse_angle")
reader.ReadFP32("ph_jumpon_end_delay")
reader.ReadFP32("ph_jumpon_depth")
reader.ReadFP32("ph_jumpon_surf_ang")
reader.ReadFP32("ph_bad_angle")
reader.ReadFP32("ph_sliding_angle")
reader.ReadFP32("ph_sliding_force_coef")
reader.ReadFP32("ph_sliding_speed_acceptable_delta")
reader.ReadU32("ph_bad_nrm_control_time")
reader.ReadFP32("ph_bad_nrm_control_loss_coef")
reader.ReadFP32("ph_crash_vel_min")
reader.ReadFP32("ph_crash_vel_max")
reader.ReadFP32("ph_mass")
reader.ReadFP32("ph_no_walk_angle")
reader.ReadFP32("ph_jump_init_speed")
reader.ReadFP32("ph_max_air_speed")
reader.ReadFP32("ph_force_coef")
reader.ReadFP32("air_control_param")
reader.ReadU32("ph_position_damping")
reader.ReadFP32("ph_position_damping_coef")
var section2 = reader.ReadArray("ph_force_fields")
for(var i = 0; section2.More(); i++)
{
	var rec = section2.ReadSection(RecStr("rec_", i, 4), false)
	rec.ReadString("bone_name")
	rec.ReadBool("is_bone")
	rec.ReadFP32("radius")
	rec.ReadVec3("offset")
	rec.ReadFP32("power")
	rec.ReadFP32("vel_coef")
	rec.ReadBool("use_mc_vel")
}
reader.ReadFP32("ph_skeleton_airr_ang_factor")
reader.ReadFP32("ph_skeleton_airr_lin_factor")
reader.ReadFP32("ph_skeleton_hinger_factor1")
reader.ReadFP32("ph_skel_fatal_impulse_factor")
reader.ReadFP32("ph_skel_shot_up_factor")
reader.ReadFP32("ph_after_death_velocity_factor")
reader.ReadFP32("jump_speed")
reader.ReadFP32("crit_damage_falloff")
reader.ReadFP32("free_damage_modifier")
reader.ReadFP32("alert_damage_modifier")
reader.ReadFP32("danger_damage_modifier")
reader.ReadU32("silent_death_interval")
reader.ReadU32("silent_death_restore_time")
reader.ReadFP32("cover_add_action_prob")
reader.ReadVec2("look_head_free_clamp_x", "ang2f")
reader.ReadVec2("look_head_free_clamp_y", "ang2f")
reader.ReadVec2("look_head_alert_clamp_x", "ang2f")
reader.ReadVec2("look_head_alert_clamp_y", "ang2f")
reader.ReadVec2("look_head_danger_clamp_x", "ang2f")
reader.ReadVec2("look_head_danger_clamp_y", "ang2f")
var section3 = reader.ReadArray("melee_attacks")
for(var i = 0; section3.More(); i++)
{
	var rec = section3.ReadSection(RecStr("rec_", i, 4), false)
	rec.ReadString("key")
	rec.ReadString("caption")
	rec.ReadU32("is_moving")
	rec.ReadU32("is_turned")
	rec.ReadU32("player_only")
	rec.ReadFP32("min_speed")
	rec.ReadFP32("min_dist")
	rec.ReadFP32("initial_dist")
	rec.ReadFP32("melee_dist")
	rec.ReadVec3("move_check")
	rec.ReadU32("check_mode")
	rec.ReadFP32("min_dot_yaw")
	rec.ReadFP32("min_dot_pitch")
	rec.ReadFP32("pick_pitch")
	rec.ReadFP32("pick_yaw")
	rec.ReadString("action")
	rec.ReadVec3("min")
	rec.ReadVec3("max")
	rec.ReadFP32("probability")
	rec.ReadBool("crit")
	rec.ReadU32("mask")
}
var section4 = reader.ReadArray("delta_presets")
for(var i = 0; section4.More(); i++)
{
	var rec = section4.ReadSection(RecStr("rec_", i, 4), false)
	rec.ReadU32("dh_preset")
	rec.ReadHintStr("motion", "animation_str")
	rec.ReadFP32("hit_min_angle")
	rec.ReadFP32("hit_max_angle")
	rec.ReadU32("body_part1")
	rec.ReadU32("body_part2")
	rec.ReadBool("is_critical")
	rec.ReadBool("is_player")
}
reader.ReadFP32("optimal_melee_dist")
reader.ReadFP32("player_melee_dist_plus")
reader.ReadFP32("group_melee_dist")
reader.ReadU32("melee_attack_to_snarl_time")
reader.ReadFP32("snarl_min_dist")
reader.ReadFP32("coll_attack_power_lb")
reader.ReadFP32("coll_attack_power_ub")
reader.ReadFP32("coll_attack_impulse_lb")
reader.ReadFP32("coll_attack_impulse_ub")
reader.ReadHintStr("bone_head", "choose")
reader.ReadHintStr("bone_camera", "choose")
reader.ReadHintStr("bone_camera_no_hud", "choose")
reader.ReadHintStr("bone_explosion_hit", "choose")
reader.ReadHintStr("bone_capsule_hit", "choose")
reader.ReadFP32("camera_height_factor")
var section5 = reader.ReadSection("actor_firsteye_cam")
section5.ReadVec2("lim_yaw")
section5.ReadVec2("lim_pitch")
section5.ReadVec2("lim_roll")
section5.ReadBool("first_eye")
section5.ReadFP32("limit_factor")
var section6 = reader.ReadSection("actor_look_cam")
section6.ReadVec2("lim_yaw")
section6.ReadVec2("lim_pitch")
section6.ReadVec2("lim_roll")
section6.ReadBool("first_eye")
section6.ReadFP32("limit_factor")
section6.ReadVec2("lim_zoom")
section6.ReadFP32("zoom_speed")
var section7 = reader.ReadSection("actor_free_cam")
section7.ReadVec2("lim_yaw")
section7.ReadVec2("lim_pitch")
section7.ReadVec2("lim_roll")
section7.ReadBool("first_eye")
section7.ReadFP32("limit_factor")
section7.ReadVec2("lim_zoom")
section7.ReadFP32("zoom_speed")
var section8 = reader.ReadSection("actor_station_cam")
section8.ReadVec2("lim_yaw")
section8.ReadVec2("lim_pitch")
section8.ReadVec2("lim_roll")
section8.ReadBool("first_eye")
section8.ReadFP32("limit_factor")
section8.ReadFP32("limit_pitch_factor")
section8.ReadFP32("limit_pitch_min_ratio")
var section9 = reader.ReadSection("actor_locked_cam")
section9.ReadVec2("lim_yaw")
section9.ReadVec2("lim_pitch")
section9.ReadVec2("lim_roll")
section9.ReadBool("first_eye")
section9.ReadFP32("limit_factor")
reader.ReadFP32("min_pforce_coef")
reader.ReadFP32("max_pforce_coef")
reader.ReadHintStr("death_init_anim", "animation_str")
reader.ReadHintStr("death_face_anim0", "animation_str")
reader.ReadHintStr("death_face_anim1", "animation_str")
reader.ReadHintStr("death_face_anim2", "animation_str")
reader.ReadHintStr("death_face_anim3", "animation_str")
reader.ReadU32("footsteps_min_interval")
reader.ReadString("event_step_left")
reader.ReadString("event_step_right")
reader.ReadString("event_step_left_hand")
reader.ReadString("event_step_right_hand")
reader.ReadString("event_jump_left")
reader.ReadString("event_jump_right")
reader.ReadString("event_die_complete")
reader.ReadString("event_die_fall")
reader.ReadString("bone_foot_left")
reader.ReadString("bone_foot_right")
reader.ReadString("bone_hand_left")
reader.ReadString("bone_hand_right")
reader.ReadU32("sound_type_unknown")
reader.ReadU32("sound_type_walk")
reader.ReadU32("sound_type_run")
reader.ReadU32("sound_type_sprint")
reader.ReadU32("sound_type_crouch")
reader.ReadU32("sound_type_jump")
reader.ReadU32("sound_type_landing")
reader.ReadFP32("fall_snd_min_impulse")
reader.ReadFP32("fall_snd_max_impulse")
reader.ReadVec3("walk_slowly_speed")
reader.ReadVec3("walk_speed")
reader.ReadVec3("run_slowly_speed")
reader.ReadVec3("run_speed")
reader.ReadVec3("sprint_speed")
reader.ReadFP32("strafe_coef")
reader.ReadFP32("backward_coef")
reader.ReadFP32("nostrafe_speed")
reader.ReadFP32("free_accel")
reader.ReadFP32("alert_accel")
reader.ReadFP32("danger_accel")
reader.ReadFP32("sprint_accel")
reader.ReadU32("move_shape_type")
reader.ReadU32("pathfind_shape_type")
reader.ReadFP32("pathfind_avoid_radius0")
reader.ReadFP32("pathfind_avoid_cost0")
reader.ReadFP32("pathfind_avoid_radius1")
reader.ReadFP32("pathfind_avoid_cost1")
reader.ReadFP32("pathfind_avoid_radius2")
reader.ReadFP32("pathfind_avoid_cost2")
reader.ReadFP32("pathfind_avoid_radius3")
reader.ReadFP32("pathfind_avoid_cost3")
reader.ReadFP32("move_avoid_radius0")
reader.ReadFP32("move_avoid_cost0")
reader.ReadFP32("move_avoid_radius1")
reader.ReadFP32("move_avoid_cost1")
reader.ReadFP32("move_avoid_radius2")
reader.ReadFP32("move_avoid_cost2")
reader.ReadFP32("move_avoid_radius3")
reader.ReadFP32("move_avoid_cost3")
reader.ReadFP32("hit_impulse_upper_bound")
reader.ReadFP32("wall_blood_distance")
reader.ReadFP32("wall_blood_dispersion", "angle, fp32")
reader.ReadBool("wall_blood_animate")
reader.ReadFP32("width_coef")
reader.ReadFP32("height_coef")
reader.ReadFP32("strict_width_coef")
reader.ReadFP32("strict_height_coef")
reader.ReadU32("danger_delay")
reader.ReadU32("uber_delay")
reader.ReadU32("alert_delay")
reader.ReadBool("full_scripted_motion_play")
reader.ReadBool("use_physics_in_movement")
reader.ReadBool("use_IKs")
reader.ReadBool("can_avoid")
reader.ReadBool("can_push")
reader.ReadFP32("scripted_push_distance")
reader.ReadFP32("scripted_push_smooth")
reader.ReadFP32("scripted_push_min_coef")
reader.ReadFP32("scripted_push_max_coef")
reader.ReadFP32("foot_step_volume")
reader.ReadFP32("net_foot_step_volume")
reader.ReadBool("correct_hill_orient")
reader.ReadU32("crit_slowdown_interval")
reader.ReadU32("crit_speedup_interval")
reader.ReadFP32("die_hard_coef")
reader.ReadFP32("overpower_radius_duplet")
reader.ReadFP32("overpower_radius_duplet_2b")
reader.ReadFP32("overpower_radius_duplet_3b")
reader.ReadFP32("overpower_radius_duplet_4b")
reader.ReadFP32("overpower_radius_abzac")
reader.ReadFP32("overpower_radius_uboynicheg")
reader.ReadFP32("overpower_radius_ashot")
reader.ReadFP32("overpower_radius_ashot_2b")
reader.ReadFP32("overpower_radius_saiga")
reader.ReadFP32("overpower_radius_ventil")
reader.ReadFP32("overpower_radius_shotgun")
reader.ReadFP32("overpower_dist_coef")
reader.ReadBool("four_square_hit")
reader.ReadFP32("assault_taran_probability")
reader.ReadFP32("wounded_level")
reader.ReadFP32("wounded_probability")
reader.ReadFP32("illuminated_radius_near")
reader.ReadFP32("illuminated_radius_far")
reader.ReadFP32("illuminated_distance")
reader.ReadU32("illuminated_react_interval")
reader.ReadFP32("illuminated_react_level")
reader.ReadFP32("burn_health_falloff")
reader.ReadFP32("burn_health_sum")
reader.ReadFP32("burn_health_border")
reader.ReadFP32("burn_health_interrupt")
reader.ReadFP32("break_attack_distance")
reader.ReadFP32("corpse_detect_distance")
reader.ReadFP32("corpse_detect_dot")
reader.ReadString("throw_weapon_locator")
reader.ReadU32("throw_weapon_time")
reader.ReadFP32("throw_weapon_speed")
reader.ReadFP32("throw_weapon_height")
reader.ReadBool("throw_weapon_force_dir")
reader.ReadFP32("hud_blood_distance")
reader.ReadFP32("hud_blood_distance_shotgun")
reader.ReadHintStr("hud_blood_particles", "choose")
reader.ReadHintStr("hud_blood_particles_gm", "choose")
reader.ReadHintStr("hud_blood_particles_shotgun", "choose")
reader.ReadHintStr("hud_blood_particles_shotgun_gm", "choose")
reader.ReadU8Array("attach_ik_types")
reader.ReadFP32("lumin_sum_max")
reader.ReadFP32("ragdoll_death_probability")
reader.ReadU32("total_flinches")
reader.ReadU32("new_threat_time")
reader.ReadFP32("new_threat_bonus")
reader.ReadU32("threat_time_disturb")
reader.ReadU32("threat_time_light_alert")
reader.ReadU32("threat_time_alert")
reader.ReadU32("threat_time_uber")
reader.ReadFP32("health_breath_0")
reader.ReadFP32("health_breath_1")
reader.ReadFP32("health_breath_2")
reader.ReadFP32("health_breath_3")
reader.ReadString("using_action")
reader.ReadHintStr("shoot_motion_rifle", "animation_str")
reader.ReadHintStr("shoot_motion_pistol", "animation_str")
reader.ReadHintStr("shoot_motion_shotgun", "animation_str")
reader.ReadHintStr("shoot_motion_grenade", "animation_str")
reader.ReadHintStr("shoot_motion_knife", "animation_str")
reader.ReadHintStr("reload_motion", "animation_str")
reader.ReadHintStr("cc_crouch_motion", "animation_str")
reader.ReadBool("safe_mode")
reader.ReadFP32("path_point_radius")
reader.ReadFP32("lean_out_speed")
reader.ReadFP32("lean_walk_slow")
reader.ReadFP32("lean_full_angle", "angle, fp32")
reader.ReadU32("scary_danger_interrupt")
reader.ReadU32("scary_max_timeout")
reader.ReadU32("scary_danger_timeout")
reader.ReadU32("wounded_critical_activation_timeout")
reader.ReadU32("wounded_lie_time")
reader.ReadU32("wounded_lie_idle_time")
reader.ReadFP32("wounded_lie_min_enemy_dist")
reader.ReadU32("wounded_lie_near_enemy_time")
reader.ReadU32("wounded_lie_min_queue_size")
reader.ReadU32("wounded_lie_max_queue_size")
reader.ReadU32("wounded_lie_min_queue_interval")
reader.ReadU32("wounded_lie_max_queue_interval")
reader.ReadFP32("cc_grenade_min_range")
reader.ReadFP32("search_follower_delta_angle")
reader.ReadU32("search_follower_timeout")
reader.ReadHintStr("enemy_spotted_delta", "animation_str")
reader.ReadFP32("scary_far_distance")
reader.ReadFP32("cheers_distance")
reader.ReadU32("ca_def_cooldown")
reader.ReadU32("ca_def_group_cooldown")
reader.ReadU32("ca_scared_to_cover_cooldown")
reader.ReadU32("ca_scared_to_cover_group_cooldown")
reader.ReadU32("ca_ambush_cover_cooldown")
reader.ReadU32("ca_ambush_cover_group_cooldown")
reader.ReadU32("ca_dodging_cooldown")
reader.ReadU32("ca_dodging_group_cooldown")
reader.ReadU32("ca_somersault_cooldown")
reader.ReadU32("ca_somersault_group_cooldown")
reader.ReadU32("ca_ambush_cooldown")
reader.ReadU32("ca_ambush_group_cooldown")
reader.ReadU32("ca_weapon_change_cooldown")
reader.ReadU32("ca_weapon_change_group_cooldown")
reader.ReadU32("ca_flanking_cooldown")
reader.ReadU32("ca_flanking_group_cooldown")
reader.ReadU32("weapon_change_danger_timeout")
reader.ReadFP32("panic_probability")
reader.ReadFP32("panic_alive_friend_dist")
reader.ReadFP32("panic_friend_corpse_dist")
reader.ReadU32("panic_cooldown_time")
reader.ReadU32("panic_danger_state_timeout")
reader.ReadU32("panic_uber_alert_state_timeout")
reader.ReadU32("panic_friend_death_max_time")
reader.ReadU32("panic_stay_in_cover_timeout")
reader.ReadU32("panic_fire_time")
reader.ReadFP32("blind_fire_prob")
reader.ReadFP32("supress_max_cover_to_enemy_yaw", "angle, fp32")
reader.ReadBool("ik_on_stairs")
reader.ReadU16Array16("default_tags")
reader.ReadFP32("lean_angle", "angle, fp32")
reader.ReadFP32("lean_speed", "angle, fp32")
reader.ReadVec3("rot_speed")
reader.ReadFP32("min_contact_speed")
reader.ReadFP32("landing_time1")
reader.ReadFP32("landing_time2")
reader.ReadFP32("jump_time")
reader.ReadFP32("jump_ground_time")
reader.ReadFP32("fall_time")
reader.ReadFP32("default_convergerence")
reader.ReadFP32("disp_base", "angle, fp32")
reader.ReadFP32("disp_aim", "angle, fp32")
reader.ReadFP32("disp_vel_factor")
reader.ReadFP32("disp_accel_factor")
reader.ReadFP32("disp_crouch_factor")
reader.ReadFP32("disp_crouch_no_acc_factor")
var section10 = reader.ReadSection("actor_animation_params")
section10.ReadFP32("fwd_l_strafe_yaw", "angle, fp32")
section10.ReadFP32("back_l_strafe_yaw", "angle, fp32")
section10.ReadFP32("fwd_r_strafe_yaw", "angle, fp32")
section10.ReadFP32("back_r_strafe_yaw", "angle, fp32")
section10.ReadFP32("l_strafe_yaw", "angle, fp32")
section10.ReadFP32("r_strafe_yaw", "angle, fp32")
reader.ReadFP32("feel_distance")
reader.ReadFP32("feel_angle")
reader.ReadFP32("feel_friend_distance")
reader.ReadFP32("feel_enemy_distance")
reader.ReadFP32("rangefinder_coef")
reader.ReadU32("k_knife_delay")
reader.ReadFP32("health_restore_pending")
reader.ReadBool("health_restore_pending_medkit")
reader.ReadFP32("health_critical")
var section11 = reader.ReadArray("health_sets")
for(var i = 0; section11.More(); i++)
{
	var rec = section11.ReadSection(RecStr("rec_", i, 4), false)
	rec.ReadFP32("threshold")
	rec.ReadFP32("restore_rate")
	rec.ReadHintStr("track", "choose")
	var particles = rec.ReadArray("particles")
	for(var j = 0; particles.More(); j++)
	{
		var rec2 = particles.ReadSection(RecStr("rec_", j, 4), false)
		rec2.ReadHintStr("name", "choose")
		rec2.ReadVec3("offset")
		rec2.ReadBool("apply_post_effects")
	}
	rec.ReadString("sound_health")
	rec.ReadString("sound_hit")
}
reader.ReadU32("slowmo_after_death_restore")
reader.ReadHintStr("slowmo_camera_track", "choose")
reader.ReadHintStr("sprint_camera_track", "choose")
reader.ReadFP32("sprint_camera_track_accrue")
reader.ReadFP32("sprint_camera_track_falloff")
reader.ReadU32("sprint_smooth_frames")
reader.ReadHintStr("crouch_camera_track", "choose")
reader.ReadFP32("stamina_inc_on_stay")
reader.ReadFP32("stamina_dec_on_sprint")
reader.ReadFP32("stamina_dec_on_jump")
reader.ReadFP32("min_stamina_for_jump")
reader.ReadFP32("min_stamina_for_sprint")
reader.ReadFP32("stamina_zero_level")
reader.ReadU32("stamina_inc_delay_after_tired")
reader.ReadU32("stamina_inc_delay_after_use")
reader.ReadU32("stamina_use_delay_after_tired")
reader.ReadFP32("walk_accel")
reader.ReadFP32("run_coef")
reader.ReadFP32("run_back_coef")
reader.ReadFP32("walk_back_coef")
reader.ReadFP32("crouch_coef")
reader.ReadFP32("climb_coef")
reader.ReadFP32("sprint_koef")
reader.ReadFP32("evade_koef")
reader.ReadFP32("joy_walk_threshold")
reader.ReadFP32("walk_strafe_coef")
reader.ReadFP32("run_strafe_coef")
reader.ReadFP32("head_delta_apply_speed")
reader.ReadFP32("lightmeter_coeff")
reader.ReadFP32("green_border")
reader.ReadFP32("yellow_border")
reader.ReadFP32("red_border")
reader.ReadFP32("slowmo_health")
reader.ReadFP32("slowmo_speed")
reader.ReadFP32("slowmo_min")
reader.ReadFP32("centering_factor")
reader.ReadFP32("centering_epsilon")
reader.ReadFP32("centering_epsilon_accuracy")
reader.ReadHintStr("snd_heartbeat", "choose")
reader.ReadHintStr("snd_breathe_00", "choose")
reader.ReadHintStr("snd_breathe_00_33", "choose")
reader.ReadHintStr("snd_breathe_33_66", "choose")
reader.ReadHintStr("snd_breathe_66_99", "choose")
reader.ReadHintStr("snd_border_33_00", "choose")
reader.ReadHintStr("snd_border_66_33", "choose")
reader.ReadHintStr("snd_bullet_fly_by", "choose")
reader.ReadHintStr("suffocation_track", "choose")
reader.ReadFP32("jump_end_track_min_speed")
reader.ReadFP32("jump_end_track_max_speed")
reader.ReadFP32("jump_idle_track_falloff")
reader.ReadHintStr("jump_in_track", "choose")
reader.ReadHintStr("jump_idle_track", "choose")
reader.ReadHintStr("jump_out_track", "choose")
reader.ReadHintStr("jump_end_track", "choose")
reader.ReadHintStr("fall_in_track", "choose")
reader.ReadHintStr("jumpover_start_track", "choose")
reader.ReadHintStr("jumpover_idle_track", "choose")
reader.ReadHintStr("jumpover_end_track", "choose")
reader.ReadHintStr("jumpon_start_track", "choose")
reader.ReadHintStr("jumpon_end_track", "choose")
reader.ReadU32("sdata_money")
reader.ReadU32("timeout_grenade_friend")
reader.ReadU32("timeout_grenade_enemy")
reader.ReadU32("hud_blood_time")
reader.ReadU32("fire_luminocity_time")
reader.ReadFP32("fire_luminocity_level")
reader.ReadFP32("movement_acceleration")
reader.ReadFP32("movement_brake")
reader.ReadU32("footstep_track_blend")
reader.ReadFP32("footstep_track_walk_factor")
reader.ReadFP32("footstep_track_run_factor")
reader.ReadFP32("footstep_track_sprint_factor")
reader.ReadHintStr("track_sprint_step_left", "choose")
reader.ReadHintStr("track_sprint_step_right", "choose")
reader.ReadHintStr("track_usual_step_left", "choose")
reader.ReadHintStr("track_usual_step_right", "choose")
reader.ReadHintStr("track_sit_step_left", "choose")
reader.ReadHintStr("track_sit_step_right", "choose")
reader.ReadHintStr("track_walk_step_left", "choose")
reader.ReadHintStr("track_walk_step_right", "choose")
reader.ReadFP32("mp_assist_reduce")
reader.ReadFP32("melee_auto_aim_dist")
reader.ReadFP32("melee_auto_aim_ang_dot")
reader.ReadFP32("monster_probability_hit")
reader.ReadFP32("bullet_probability_hit")
reader.ReadFP32("boost_threshold")
reader.ReadU32("npc_wounded_critical_timeout")
reader.ReadU32("after_load_damage_restore_timeout")
reader.ReadU32("sprint_crit_cooldown")
reader.ReadFP32("jump_power_reduce")
reader.ReadFP32("jump_power_min")
reader.ReadFP32("jump_power_weak")
reader.ReadFP32("jump_power_restore")
reader.ReadHintStr("snd_tired_for_jump", "choose")
reader.ReadFP32("player_vision_range")
reader.ReadFP32("player_vision_bwd_range")
reader.ReadFP32("player_vision_fov", "angle, fp32")
reader.ReadU32("player_vision_min_update_time")
reader.ReadFP32("player_vision_luminocity_fac")
reader.ReadFP32("player_vision_luminocity_factor")
reader.ReadFP32("player_vision_velocity_fac")
reader.ReadFP32("player_vision_decrease_value")
reader.ReadFP32("player_vision_min_lum_threshold")
reader.ReadFP32("player_vision_min_threshold")
reader.ReadFP32("player_vision_threat_threshold")
reader.ReadFP32("player_vision_light_alert_threshold")
reader.ReadFP32("player_vision_vis_threshold")
reader.ReadFP32("player_vision_lum_min_distance")
reader.ReadFP32("player_vision_surv_threat_threshold")
reader.ReadFP32("player_vision_surv_light_alert_threshold")
reader.ReadFP32("player_vision_surv_vis_threshold")
reader.ReadFP32("player_vision_surv_lum_min_distance")
reader.ReadU32("ghost_max_time")
reader.ReadU32("ghost_strict_time")
reader.ReadU32("ghost_danger_time")
reader.ReadFP32("stealth_inert")
reader.ReadFP32("stealth_mul_coef")
reader.ReadFP32("stealth_pow_coef")
reader.ReadFP32("stealth_speed_add_coef")
reader.ReadFP32("stealth_speed_mul_coef")
reader.ReadFP32("vel_threshold")
reader.ReadFP32("foliage_coef")
reader.ReadFP32("foliage_fetch_radius")
reader.ReadFP32("max_head_bias_z_value")
reader.ReadString("neck_bone")
reader.ReadFP32("incl_rate")
reader.ReadFP32("cheat_bias")
reader.ReadFP32("fast_drop_show_ui_delay")
reader.ReadFP32("fast_drop_show_anim_delay")
reader.ReadU32("max_save_items_by_type")
reader.ReadFP32("melee_check_npc_height")
reader.ReadVec2("melee_check_box_wh")
reader.ReadVec3("melee_check_bb_size")
reader.ReadFP32("melee_check_ground_offset")
reader.ReadHintStr("gun2pistol_motion", "animation_str")
reader.ReadHintStr("pistol2gun_motion", "animation_str")
reader.ReadHintStr("gun2gun_motion", "animation_str")
reader.ReadHintStr("gasmask_dress_motion", "animation_str")
reader.ReadHintStr("gasmask_remove_motion", "animation_str")
reader.ReadHintStr("knife_fast_stab", "animation_str")
reader.ReadFP32("aim_mult_linear")
reader.ReadFP32("aim_mult_exp")
