// Auto-generated file

reader.ReadU16("version")
reader.ReadU32("slot")
reader.ReadFP32("control_inertion_factor")
reader.ReadHint("flags", "flags8")
reader.ReadU8("flags")
reader.ReadU8("slot_max_num")
reader.ReadU32("animation_slot")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadString("hr_class")
reader.ReadString("using_action")
reader.ReadString("using_action_replace")
reader.ReadFP32("take_impulse")
reader.ReadHintStr("take_sound", "sound")
var section2 = reader.ReadSection("icon")
section2.ReadString("texture")
section2.ReadVec4("tex_rect")
section2.ReadString("technics")
section2.ReadString("shader")
section2.ReadVec4("wnd_rect")
section2.ReadVec4i("color")
section2.ReadU32("scale")
section2.ReadU8("h_alignment")
section2.ReadU8("v_alignment")
section2.ReadVec2("icon_offset")
section2.ReadFP32("rotate_speed")
section2.ReadVec2("font_pos")
reader.ReadHintStr("hud_visual", "ref_model")
reader.ReadString("anim_time")
reader.ReadHintStr("camera_track_idle", "camera_track, str_shared")
reader.ReadHintStr("camera_track_dress", "camera_track, str_shared")
reader.ReadHintStr("snd_dress", "sound")
reader.ReadHintStr("camera_track_remove", "camera_track, str_shared")
reader.ReadHintStr("snd_remove", "sound")
reader.ReadString("device_time_anim")
reader.ReadString("device_dress_anim")
reader.ReadString("device_remove_anim")
reader.ReadString("device_idle_anim")
reader.ReadHintStr("snd_idle", "sound")
reader.ReadU32("hud_device_id")
reader.ReadString("gasmask_take_off_anim")
reader.ReadString("gasmask_change_filter_anim")
reader.ReadFP32("after_take_off_time")
reader.ReadString("gasmask_filter_id")
reader.ReadU32("gasmask_replace_interval")
reader.ReadHintStr("indoor_hud_gasmask", "texture, str_shared")
reader.ReadHintStr("indoor_hud_gasmask_dist", "texture, str_shared")
reader.ReadHintStr("outdoor_hud_gasmask", "texture, str_shared")
reader.ReadHintStr("outdoor_hud_gasmask_dist", "texture, str_shared")
reader.ReadString("event_enable_crash")
reader.ReadString("event_disable_crash")
var section3 = reader.ReadArray("gasmask_health_sets")
for(var i = 0; section3.More(); i++)
{
	var section4 = section3.ReadSection(RecStr("rec_", i, 4), false)
	section4.ReadFP32("threshold")
	section4.ReadHintStr("texture_dif", "texture, str_shared")
	section4.ReadHintStr("texture_dis", "texture, str_shared")
	section4.ReadHintStr("crash_bone", "locator_str")
}
reader.ReadMatrix44("hud")
reader.ReadBool("allow_inertion")
reader.ReadFP32("tend_to_speed")
reader.ReadFP32("fov_coef_tend")
reader.ReadHintStr("camera_track_take_off", "camera_track, str_shared")
reader.ReadHintStr("snd_take_off", "sound")
reader.ReadHintStr("camera_gasmask_blink", "camera_track, str_shared")
