// Auto-generated file

reader.ReadU16("version")
reader.ReadU32("slot")
reader.ReadFP32("control_inertion_factor")
reader.ReadHint("flags", "flags8")
reader.ReadU8("flags")
reader.ReadU8("slot_max_num")
reader.ReadU32("animation_slot")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadString("hr_class")
reader.ReadString("using_action")
reader.ReadString("using_action_replace")
reader.ReadFP32("take_impulse")
reader.ReadHintStr("take_sound", "sound")
var section2 = reader.ReadSection("icon")
section2.ReadString("texture")
section2.ReadVec4("tex_rect")
section2.ReadString("technics")
section2.ReadString("shader")
section2.ReadVec4("wnd_rect")
section2.ReadVec4i("color")
section2.ReadU32("scale")
section2.ReadU8("h_alignment")
section2.ReadU8("v_alignment")
section2.ReadVec2("icon_offset")
section2.ReadFP32("rotate_speed")
section2.ReadVec2("font_pos")
reader.ReadFP32("k_dist")
reader.ReadFP32("k_disp")
reader.ReadFP32("k_hit")
reader.ReadFP32("k_impulse")
reader.ReadFP32("k_pierce")
reader.ReadBool("tracer")
reader.ReadS32("buck_shot")
reader.ReadFP32("wm_size")
reader.ReadS32("box_size")
reader.ReadU32("type")
reader.ReadBool("valuable")
reader.ReadBool("balanced")
reader.ReadU32("cost")
reader.ReadU16("magazine")
reader.ReadU32("cost_sell")
reader.ReadU16("magazine_sell")
reader.ReadString("using_action")
reader.ReadFP32("hit_power")
reader.ReadFP32("hit_impulse")
reader.ReadFP32("fire_distance")
reader.ReadFP32("fire_dispersion")
reader.ReadFP32("bullet_speed")
reader.ReadFP32("fly_dump")
reader.ReadFP32("ang_dump")
reader.ReadFP32("not_fly_speed")
reader.ReadVec3("startup_rotation")
reader.ReadFP32("penetrate_depth")
reader.ReadFP32("wallmark_size")
reader.ReadFP32("fade_impulse_coef")
reader.ReadString("material")
reader.ReadHintStr("arrow_bone", "bone_str")
reader.ReadHintStr("bullet_particles", "particles, str_shared")
reader.ReadFP32("direct_hit_distance")
