// Auto-generated file

reader.ReadU16("version")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadFP32("dispersion_base")
reader.ReadFP32("dispersion_aim")
reader.ReadFP32("dispersion_move_factor")
reader.ReadFP32("dispersion_inc")
reader.ReadFP32("dispersion_min")
reader.ReadFP32("dispersion_max")
reader.ReadFP32("dispersion_dec")
var section2 = reader.ReadSection("axis_disp")
section2.ReadFP32("left_axis")
section2.ReadFP32("up_axis")
section2.ReadFP32("right_axis")
section2.ReadFP32("down_axis")
reader.ReadFP32("hit_power")
reader.ReadFP32("hit_impulse")
reader.ReadFP32("fire_distance")
reader.ReadFP32("bullet_speed")
reader.ReadFP32("min_radius")
reader.ReadFP32("max_radius")
reader.ReadString("fire_bone")
reader.ReadString("shell_bone")
reader.ReadVec4("light_color", "color, vec4f")
reader.ReadFP32("light_range")
reader.ReadFP32("light_var_color")
reader.ReadFP32("light_var_range")
reader.ReadFP32("light_time")
reader.ReadString("light_coloranim")
reader.ReadVec3("light_point")
reader.ReadHintStr("flame_particles", "particles, str_shared")
reader.ReadHintStr("smoke_particles", "particles, str_shared")
reader.ReadHintStr("shot_particles", "particles, str_shared")
reader.ReadHintStr("shell_particles", "particles, str_shared")
reader.ReadFP32("shell_occlusion_distance")
reader.ReadBool("shell_drop")
reader.ReadFP32("rpm")
reader.ReadString("ammo_class")
var section3 = reader.ReadSection("ammo_class")
section3.ReadFP32("k_dist")
section3.ReadFP32("k_disp")
section3.ReadFP32("k_hit")
section3.ReadFP32("k_impulse")
section3.ReadFP32("k_pierce")
section3.ReadFP32("k_monster_coef")
section3.ReadBool("tracer")
section3.ReadS32("buck_shot")
section3.ReadFP32("wm_size")
section3.ReadString("bullet_particles")
section3.ReadBool("can_be_unlimited")
section3.ReadBool("explosive")
section3.ReadBool("unlimited")
section3.ReadBool("valuable")
section3.ReadU32("type")
reader.ReadString("bullet_type")
reader.ReadFP32("heat_inertion")
reader.ReadFP32("heat_level_cooled")
reader.ReadHintStr("snd_steam_prefix", "sound")
reader.ReadFP32("snd_steam_volume")
reader.ReadString("type_kulemet")
reader.ReadString("bullet_type")
