// Auto-generated file

reader.ReadU16("version")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadFP32("coll_attack_power_lb")
reader.ReadFP32("coll_attack_power_ub")
reader.ReadFP32("coll_attack_impulse_lb")
reader.ReadFP32("coll_attack_impulse_ub")
reader.ReadFP32("min_distance")
reader.ReadFP32("max_distance")
reader.ReadU32("min_cooldown_time")
reader.ReadU32("max_cooldown_time")
reader.ReadU32("min_hide_time")
reader.ReadU32("max_hide_time")
reader.ReadFP32("hide_damage")
reader.ReadString("bone_rotation")
reader.ReadHintStr("snd_idle_prefix", "sound")
reader.ReadHintStr("snd_attack_prefix", "sound")
reader.ReadU8("hit_type")
