// Auto-generated file

reader.ReadU16("version")
reader.ReadU32("slot")
reader.ReadFP32("control_inertion_factor")
reader.ReadHint("flags", "flags8")
reader.ReadU8("flags")
reader.ReadU8("slot_max_num")
reader.ReadU32("animation_slot")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadString("hr_class")
reader.ReadString("using_action")
reader.ReadString("using_action_replace")
reader.ReadFP32("take_impulse")
reader.ReadHintStr("take_sound", "sound")
var section2 = reader.ReadSection("icon")
section2.ReadString("texture")
section2.ReadVec4("tex_rect")
section2.ReadString("technics")
section2.ReadString("shader")
section2.ReadVec4("wnd_rect")
section2.ReadVec4i("color")
section2.ReadU32("scale")
section2.ReadU8("h_alignment")
section2.ReadU8("v_alignment")
section2.ReadVec2("icon_offset")
section2.ReadFP32("rotate_speed")
section2.ReadVec2("font_pos")
reader.ReadHintStr("hud_visual", "ref_model")
reader.ReadString("anim_time")
reader.ReadHintStr("camera_track_idle", "camera_track, str_shared")
reader.ReadHintStr("camera_track_dress", "camera_track, str_shared")
reader.ReadHintStr("snd_dress", "sound")
reader.ReadHintStr("camera_track_remove", "camera_track, str_shared")
reader.ReadHintStr("snd_remove", "sound")
reader.ReadString("device_time_anim")
reader.ReadString("device_dress_anim")
reader.ReadString("device_remove_anim")
reader.ReadString("device_idle_anim")
reader.ReadHintStr("snd_idle", "sound")
reader.ReadU32("hud_device_id")
reader.ReadFP32("threshold_warning")
reader.ReadFP32("threshold_off")
reader.ReadHintStr("camera_track_fade_in", "camera_track, str_shared")
reader.ReadHintStr("camera_track_fade_out", "camera_track, str_shared")
reader.ReadHintStr("camera_track_fade_out_quick", "camera_track, str_shared")
reader.ReadHintStr("snd_lowbat", "sound")
reader.ReadFP32("power_consumption")
reader.ReadMatrix44("hud")
reader.ReadBool("allow_inertion")
reader.ReadFP32("tend_to_speed")
reader.ReadFP32("fov_coef_tend")
reader.ReadFP32("light_brightness")
reader.ReadFP32("light_cone", "angle, fp32")
reader.ReadFP32("light_range")
reader.ReadHintStr("light_texture", "texture, str_shared")
reader.ReadU8("light_scurve")
reader.ReadBool("light_shadowed")
reader.ReadVec3("light_offset")
