// Auto-generated file

reader.ReadU16("version")
reader.ReadU32("slot")
reader.ReadFP32("control_inertion_factor")
reader.ReadHint("flags", "flags8")
reader.ReadU8("flags")
reader.ReadU8("slot_max_num")
reader.ReadU32("animation_slot")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadString("hr_class")
reader.ReadString("using_action")
reader.ReadString("using_action_replace")
reader.ReadFP32("take_impulse")
reader.ReadHintStr("take_sound", "sound")
var section2 = reader.ReadSection("icon")
section2.ReadString("texture")
section2.ReadVec4("tex_rect")
section2.ReadString("technics")
section2.ReadString("shader")
section2.ReadVec4("wnd_rect")
section2.ReadVec4i("color")
section2.ReadU32("scale")
section2.ReadU8("h_alignment")
section2.ReadU8("v_alignment")
section2.ReadVec2("icon_offset")
section2.ReadFP32("rotate_speed")
section2.ReadVec2("font_pos")
reader.ReadHintStr("hud_visual", "ref_model")
reader.ReadString("anim_time")
reader.ReadString("anim_map_0_draw")
reader.ReadString("anim_map_0_holster")
reader.ReadString("anim_map_1_holster")
reader.ReadString("anim_map_2_holster")
reader.ReadString("anim_map_3_holster")
reader.ReadString("anim_map_0_idle")
reader.ReadString("anim_map_0_walk")
reader.ReadString("anim_map_0_run")
reader.ReadString("anim_map_0_to_1")
reader.ReadString("anim_map_0_to_2")
reader.ReadString("anim_map_0_sprint")
reader.ReadString("anim_map_1_idle")
reader.ReadString("anim_map_1_walk")
reader.ReadString("anim_map_1_run")
reader.ReadString("anim_map_1_to_0")
reader.ReadString("anim_map_1_to_3")
reader.ReadString("anim_map_2_idle")
reader.ReadString("anim_map_2_walk")
reader.ReadString("anim_map_2_run")
reader.ReadString("anim_map_2_to_0")
reader.ReadString("anim_map_2_to_3")
reader.ReadString("anim_map_3_idle")
reader.ReadString("anim_map_3_walk")
reader.ReadString("anim_map_3_run")
reader.ReadString("anim_map_3_to_1")
reader.ReadString("anim_map_3_to_2")
reader.ReadHintStr("snd_map_0_draw", "sound")
reader.ReadHintStr("snd_map_0_holster", "sound")
reader.ReadHintStr("snd_map_0_to_1", "sound")
reader.ReadHintStr("snd_map_0_to_2", "sound")
reader.ReadHintStr("snd_map_1_to_0", "sound")
reader.ReadHintStr("snd_map_1_to_3", "sound")
reader.ReadHintStr("snd_map_2_to_0", "sound")
reader.ReadHintStr("snd_map_2_to_3", "sound")
reader.ReadHintStr("snd_map_3_to_1", "sound")
reader.ReadHintStr("snd_map_3_to_2", "sound")
reader.ReadHintStr("map_change_sound", "sound")
reader.ReadHintStr("mission_change_sound", "sound")
reader.ReadString("start_wick")
reader.ReadString("stop_wick")
reader.ReadHintStr("milestone_change_trk", "camera_track, str_shared")
var section3 = reader.ReadArray("milestones")
for(var i = 0; section3.More(); i++)
{
	var section4 = section3.ReadSection(RecStr("rec_", i, 4), false)
	section4.ReadString("name")
	
	var section5 = section4.ReadArray("datas")
	for(var j = 0; section5.More(); j++)
	{
		var section6 = section5.ReadSection(RecStr("rec_", j, 4), false)
		section6.ReadString("name")
		section6.ReadHintStr("tex_map", "texture, str_shared")
		section6.ReadHintStr("tex_task", "texture, str_shared")
	}
}
reader.ReadMatrix44("hud")
reader.ReadBool("allow_inertion")
reader.ReadFP32("tend_to_speed")
reader.ReadFP32("fov_coef_tend")
reader.ReadHintStr("wick_bone", "bone_id")
reader.ReadString("wick_particles")
reader.ReadHintStr("wick_color_anim", "ref_coloranim")
reader.ReadFP32("wick_light_radius")
reader.ReadFP32("wick_near_plane")
reader.ReadFP32("wick_light_brightness")
reader.ReadVec4("wick_light_color", "color, vec4f")
reader.ReadBool("wick_light_shadow")
reader.ReadVec3("wick_light_offset")
reader.ReadFP32("wick_dev_way_angle", "angle, fp32")
reader.ReadFP32("wick_dev_move_factor")
reader.ReadFP32("wick_dev_max_angle", "angle, fp32")
