// Auto-generated file

reader.ReadU16("version")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadVec3("ph_box0_center")
reader.ReadVec3("ph_box0_size")
reader.ReadVec3("ph_box1_center")
reader.ReadVec3("ph_box1_size")
reader.ReadVec3("ph_box2_center")
reader.ReadVec3("ph_box2_size")
reader.ReadFP32("ph_crash_vel_min")
reader.ReadFP32("ph_crash_vel_max")
reader.ReadFP32("ph_mass")
reader.ReadFP32("air_control_param")
reader.ReadFP32("ph_skeleton_airr_ang_factor")
reader.ReadFP32("ph_skeleton_airr_lin_factor")
reader.ReadFP32("ph_skeleton_hinger_factor1")
reader.ReadS32("ph_skeleton_ddelay")
reader.ReadFP32("ph_skel_fatal_impulse_factor")
reader.ReadFP32("ph_skel_shot_up_factor")
reader.ReadFP32("ph_after_death_velocity_factor")
reader.ReadFP32("jump_speed")
reader.ReadFP32("crit_damage_falloff")
var section2 = reader.ReadArray("melee_attacks")
reader.ReadFP32("optimal_melee_dist")
reader.ReadFP32("player_melee_dist_plus")
reader.ReadFP32("coll_attack_power_lb")
reader.ReadFP32("coll_attack_power_ub")
reader.ReadFP32("coll_attack_impulse_lb")
reader.ReadFP32("coll_attack_impulse_ub")
reader.ReadHintStr("bone_head", "bone_str")
reader.ReadHintStr("bone_explosion_hit", "bone_str")
reader.ReadHintStr("bone_capsule_hit", "bone_str")
reader.ReadFP32("camera_height_factor")
var section3 = reader.ReadSection("actor_firsteye_cam")
section3.ReadVec2("lim_yaw")
section3.ReadVec2("lim_pitch")
section3.ReadVec2("lim_roll")
section3.ReadBool("first_eye")
section3.ReadFP32("limit_factor")
var section4 = reader.ReadSection("actor_ladder_cam")
section4.ReadVec2("lim_yaw")
section4.ReadVec2("lim_pitch")
section4.ReadVec2("lim_roll")
section4.ReadBool("first_eye")
section4.ReadFP32("limit_factor")
var section5 = reader.ReadSection("actor_look_cam")
section5.ReadVec2("lim_yaw")
section5.ReadVec2("lim_pitch")
section5.ReadVec2("lim_roll")
section5.ReadBool("first_eye")
section5.ReadFP32("limit_factor")
section5.ReadVec2("lim_zoom")
section5.ReadFP32("zoom_speed")
var section6 = reader.ReadSection("actor_free_cam")
section6.ReadVec2("lim_yaw")
section6.ReadVec2("lim_pitch")
section6.ReadVec2("lim_roll")
section6.ReadBool("first_eye")
section6.ReadFP32("limit_factor")
section6.ReadVec2("lim_zoom")
section6.ReadFP32("zoom_speed")
var section7 = reader.ReadSection("actor_station_cam")
section7.ReadVec2("lim_yaw")
section7.ReadVec2("lim_pitch")
section7.ReadVec2("lim_roll")
section7.ReadBool("first_eye")
section7.ReadFP32("limit_factor")
section7.ReadFP32("limit_pitch_factor")
section7.ReadFP32("limit_pitch_min_ratio")
var section8 = reader.ReadSection("actor_locked_cam")
section8.ReadVec2("lim_yaw")
section8.ReadVec2("lim_pitch")
section8.ReadVec2("lim_roll")
section8.ReadBool("first_eye")
section8.ReadFP32("limit_factor")
reader.ReadFP32("min_pforce_coef")
reader.ReadFP32("max_pforce_coef")
reader.ReadHintStr("death_init_anim", "animation_str")
reader.ReadHintStr("death_face_anim0", "animation_str")
reader.ReadHintStr("death_face_anim1", "animation_str")
reader.ReadHintStr("death_face_anim2", "animation_str")
reader.ReadHintStr("death_face_anim3", "animation_str")
reader.ReadU32("footsteps_min_interval")
reader.ReadString("event_step_left")
reader.ReadString("event_step_right")
reader.ReadString("event_step_left_hand")
reader.ReadString("event_step_right_hand")
reader.ReadString("event_jump_left")
reader.ReadString("event_jump_right")
reader.ReadString("bone_foot_left")
reader.ReadString("bone_foot_right")
reader.ReadString("bone_hand_left")
reader.ReadString("bone_hand_right")
reader.ReadU32("sound_type_unknown")
reader.ReadU32("sound_type_walk")
reader.ReadU32("sound_type_run")
reader.ReadU32("sound_type_sprint")
reader.ReadU32("sound_type_crouch")
reader.ReadU32("sound_type_jump")
reader.ReadFP32("walk_slowly_speed")
reader.ReadFP32("walk_speed")
reader.ReadFP32("run_speed")
reader.ReadFP32("sprint_speed")
reader.ReadFP32("strafe_coef")
reader.ReadFP32("backward_coef")
reader.ReadFP32("nostrafe_speed")
reader.ReadFP32("free_accel")
reader.ReadFP32("alert_accel")
reader.ReadFP32("danger_accel")
reader.ReadFP32("sprint_accel")
reader.ReadU32("move_shape_type")
reader.ReadU32("pathfind_shape_type")
reader.ReadFP32("pathfind_avoid_radius0")
reader.ReadFP32("pathfind_avoid_cost0")
reader.ReadFP32("pathfind_avoid_radius1")
reader.ReadFP32("pathfind_avoid_cost1")
reader.ReadFP32("pathfind_avoid_radius2")
reader.ReadFP32("pathfind_avoid_cost2")
reader.ReadFP32("pathfind_avoid_radius3")
reader.ReadFP32("pathfind_avoid_cost3")
reader.ReadFP32("move_avoid_radius0")
reader.ReadFP32("move_avoid_cost0")
reader.ReadFP32("move_avoid_radius1")
reader.ReadFP32("move_avoid_cost1")
reader.ReadFP32("move_avoid_radius2")
reader.ReadFP32("move_avoid_cost2")
reader.ReadFP32("move_avoid_radius3")
reader.ReadFP32("move_avoid_cost3")
reader.ReadFP32("hit_impulse_upper_bound")
reader.ReadFP32("width_coef")
reader.ReadFP32("height_coef")
reader.ReadFP32("strict_width_coef")
reader.ReadFP32("strict_height_coef")
reader.ReadU32("danger_delay")
reader.ReadU32("uber_delay")
reader.ReadU32("alert_delay")
reader.ReadBool("full_scripted_motion_play")
reader.ReadBool("use_physics_in_movement")
reader.ReadBool("use_IKs")
reader.ReadBool("can_avoid")
reader.ReadBool("can_push")
reader.ReadFP32("scripted_push_distance")
reader.ReadFP32("scripted_push_smooth")
reader.ReadFP32("foot_step_volume")
var section9 = reader.ReadArray("inventory_keys")
for(var i = 0; section9.More(); i++)
{
	var section10 = section9.ReadSection(RecStr("rec_", i, 4), false)
	section10.ReadU8("priority")
	section10.ReadU8Array("slots")
}
reader.ReadFP32("health_breath_0")
reader.ReadFP32("health_breath_1")
reader.ReadFP32("health_breath_2")
reader.ReadFP32("health_breath_3")
reader.ReadString("using_action")
reader.ReadHintStr("shoot_motion", "animation_str")
reader.ReadBool("safe_mode")
var section17 = reader.ReadSection("arms_params")
section17.ReadHintStr("hud_visual", "ref_model")
section17.ReadString("anim_time")
section17.ReadMatrix44("hud")
section17.ReadBool("allow_inertion")
section17.ReadFP32("tend_to_speed")
section17.ReadFP32("fov_coef_tend")
section17.ReadHintStr("green_bone", "bone_id")
section17.ReadHintStr("yellow_bone", "bone_id")
section17.ReadHintStr("red_bone", "bone_id")
section17.ReadHintStr("camera_timer_track", "camera_track, str_shared")
section17.ReadString("anim_time_0")
section17.ReadString("anim_time_1")
section17.ReadString("anim_time_2")
section17.ReadString("anim_timer_0")
reader.ReadFP32("lean_angle", "angle, fp32")
reader.ReadFP32("lean_speed", "angle, fp32")
reader.ReadVec3("rot_speed")
reader.ReadFP32("min_contact_speed")
reader.ReadFP32("min_stamina_for_jump")
reader.ReadFP32("landing_time1")
reader.ReadFP32("landing_time2")
reader.ReadFP32("jump_time")
reader.ReadFP32("jump_ground_time")
reader.ReadFP32("fall_time")
reader.ReadFP32("disp_base", "angle, fp32")
reader.ReadFP32("disp_vel_factor")
reader.ReadFP32("disp_accel_factor")
reader.ReadFP32("disp_crouch_factor")
reader.ReadFP32("disp_crouch_no_acc_factor")
var section18 = reader.ReadSection("actor_animation_params")
section18.ReadFP32("fwd_l_strafe_yaw", "angle, fp32")
section18.ReadFP32("back_l_strafe_yaw", "angle, fp32")
section18.ReadFP32("fwd_r_strafe_yaw", "angle, fp32")
section18.ReadFP32("back_r_strafe_yaw", "angle, fp32")
section18.ReadFP32("l_strafe_yaw", "angle, fp32")
section18.ReadFP32("r_strafe_yaw", "angle, fp32")
reader.ReadFP32("feel_distance")
reader.ReadFP32("feel_angle")
reader.ReadFP32("feel_friend_distance")
reader.ReadU32("k_knife_delay")
reader.ReadFP32("health_restore_pending")
reader.ReadBool("health_restore_pending_medkit")
reader.ReadFP32("health_critical")
var section19 = reader.ReadArray("health_sets")
for(var j = 0; section19.More(); j++)
{
	var section20 = section19.ReadSection(RecStr("rec_", j, 4), false)
	section20.ReadFP32("threshold")
	section20.ReadFP32("restore_rate")
	section20.ReadString("track")
	section20.ReadString("particles")
	section20.ReadString("sound_health")
	section20.ReadString("sound_hit")
}
reader.ReadU8("attack_hit_type")
reader.ReadU32("slowmo_after_death_restore")
reader.ReadHintStr("slowmo_camera_track", "camera_track, str_shared")
reader.ReadHintStr("sprint_in_camera_track", "camera_track, str_shared")
reader.ReadHintStr("sprint_camera_track", "camera_track, str_shared")
reader.ReadHintStr("sprint_out_camera_track", "camera_track, str_shared")
reader.ReadHintStr("ladder_camera_track", "camera_track, str_shared")
reader.ReadFP32("stamina_inc_on_sprint")
reader.ReadFP32("stamina_inc_on_walk")
reader.ReadFP32("stamina_inc_on_run")
reader.ReadFP32("stamina_inc_on_stay")
reader.ReadFP32("stamina_dec_on_sprint")
reader.ReadFP32("min_stamina_for_sprint")
reader.ReadFP32("walk_accel")
reader.ReadFP32("run_coef")
reader.ReadFP32("run_back_coef")
reader.ReadFP32("walk_back_coef")
reader.ReadFP32("crouch_coef")
reader.ReadFP32("climb_coef")
reader.ReadFP32("sprint_koef")
reader.ReadFP32("joy_walk_threshold")
reader.ReadFP32("walk_strafe_coef")
reader.ReadFP32("run_strafe_coef")
reader.ReadFP32("lightmeter_coeff")
reader.ReadFP32("green_border")
reader.ReadFP32("yellow_border")
reader.ReadFP32("red_border")
var section24 = reader.ReadArray("hit_camera_tracks")
for(var k = 0; section24.More(); k++)
{
	var section25 = section24.ReadSection(RecStr("rec_", k, 4), false)
	section25.ReadU32("id")
	section25.ReadBool("force_restart")
	section25.ReadHintStr("front", "camera_track, str_shared")
	section25.ReadHintStr("back", "camera_track, str_shared")
	section25.ReadHintStr("left", "camera_track, str_shared")
	section25.ReadHintStr("right", "camera_track, str_shared")
	section25.ReadHintStr("front_left", "camera_track, str_shared")
	section25.ReadHintStr("front_right", "camera_track, str_shared")
	section25.ReadHintStr("back_left", "camera_track, str_shared")
	section25.ReadHintStr("back_right", "camera_track, str_shared")
}
reader.ReadFP32("slowmo_health")
reader.ReadFP32("slowmo_speed")
reader.ReadFP32("slowmo_min")
reader.ReadFP32("centering_factor")
reader.ReadFP32("centering_epsilon")
reader.ReadFP32("centering_epsilon_accuracy")
reader.ReadHintStr("snd_heartbeat", "sound")
reader.ReadHintStr("snd_breathe_00", "sound")
reader.ReadHintStr("snd_breathe_00_33", "sound")
reader.ReadHintStr("snd_breathe_33_66", "sound")
reader.ReadHintStr("snd_breathe_66_99", "sound")
reader.ReadHintStr("snd_border_33_00", "sound")
reader.ReadHintStr("snd_border_66_33", "sound")
reader.ReadHintStr("snd_bullet_fly_by", "sound")
reader.ReadHintStr("suffocation_track", "camera_track, str_shared")
reader.ReadString("sdata_money")
reader.ReadU32("timeout_grenade_friend")
reader.ReadU32("timeout_grenade_enemy")
reader.ReadFP32("npc_free_damage_modifier")
reader.ReadFP32("npc_alert_damage_modifier")
reader.ReadFP32("npc_danger_damage_modifier")
reader.ReadFP32("hud_blood_distance")
reader.ReadString("hud_blood_particles")
reader.ReadU32("fire_luminocity_time")
reader.ReadFP32("fire_luminocity_level")
reader.ReadFP32("ladder_link_angle")
var section28 = reader.ReadArray("blood_hit_sets")
for(var l = 0; section28.More(); l++)
{
	var section29 = section28.ReadSection(RecStr("rec_", l, 4), false)
	section29.ReadString("particles")
	section29.ReadString("particles_m")
}
reader.ReadFP32("monster_probability_hit")
reader.ReadFP32("bullet_probability_hit")
reader.ReadFP32("boost_threshold")
var section33 = reader.ReadArray("balance_set")
for(var m = 0; section33.More(); m++)
{
	var section34 = section33.ReadSection(RecStr("rec_", m, 4), false)
	section34.ReadFP32("health_restore")
	section34.ReadFP32("loot")
	section34.ReadFP32("loot_money")
	section34.ReadFP32("hit_power")
	section34.ReadFP32("wound_power")
	section34.ReadFP32("monster_power")
	section34.ReadFP32("bullets")
	section34.ReadFP32("medkit")
	section34.ReadFP32("filter")
	section34.ReadFP32("mask")
	section34.ReadFP32("discharge")
	section34.ReadFP32("weapon_price")
	section34.ReadFP32("weapon_cost")
}
var section38 = reader.ReadArray("balance_set_xbox")
for(var n = 0; section38.More(); n++)
{
	var section39 = section38.ReadSection(RecStr("rec_", n, 4), false)
	section39.ReadFP32("health_restore")
	section39.ReadFP32("loot")
	section39.ReadFP32("loot_money")
	section39.ReadFP32("hit_power")
	section39.ReadFP32("wound_power")
	section39.ReadFP32("monster_power")
	section39.ReadFP32("bullets")
	section39.ReadFP32("medkit")
	section39.ReadFP32("filter")
	section39.ReadFP32("mask")
	section39.ReadFP32("discharge")
	section39.ReadFP32("weapon_price")
	section39.ReadFP32("weapon_cost")
}