// Auto-generated file

reader.ReadU16("version")
var section1 = reader.ReadSection("__edit")
section1.ReadString("caption")
reader.ReadBool("editable")
reader.ReadBool("visible_for_ai")
reader.ReadBool("block_ai_los")
reader.ReadBool("collideable")
reader.ReadString("collision_sound")
reader.ReadHintStr("collision_track", "camera_track, str_shared")
reader.ReadU32("collision_interval")
reader.ReadFP32("collision_move")
reader.ReadHintStr("die_color_animator", "ref_coloranim")
reader.ReadBool("collide_ignore_static")
reader.ReadFP32("backlight_range_cut")
reader.ReadFP32("backlight_inertion")
reader.ReadFP32("backlight_dispersion")
reader.ReadBool("backlight_dispersion_show")
reader.ReadFP32("power_consumption_ex")
reader.ReadFP32("overlight_border")
reader.ReadFP32("overlight_power")
