var already_printed = new Object // unknown classes

this.get_clsid = function(crc)
{
	var clsid = hash_table[crc];
	
	if(!clsid)
	{
		if(!already_printed[crc])
		{
			print("unknown block clsid found, crc ", crc);
			already_printed[crc] = true;
		}
		
		return "";
	}
	else	
		return clsid;
}

// taken from https://github.com/iOrange/MetroEX/blob/wip_v05/src/metro/scripts/BlockFactory.cpp
var clsids = [
	"actions/action_check_slot",
	"actions/action_cover_anchor",
	"actions/action_data_add",
	"actions/action_data_check",
	"actions/action_data_remove",
	"actions/action_dialog",
	"actions/action_loader_diary_open",
	"actions/action_move2camera",
	"actions/action_pd_add",
	"actions/action_pd_check",
	"actions/action_pd_reset",
	"actions/action_set_interest",
	"actions/action_set_interest_ex",
	"actions/action_unreachable_enemy_anchor",
	"actions/activate-deactivate",
	"actions/actor movement",
	"actions/actor movement allowed",
	"actions/actor movement ex",
	"actions/add_diary",
	"actions/add_postcard",
	"actions/ai/aqua_female face enemy",
	"actions/ai/arahind face enemy",
	"actions/ai/arahind female mode",
	"actions/ai/arahind jump",
	"actions/ai/arahind light reaction",
	"actions/ai/CHEAT force rotate",
	"actions/ai/cover combat",
	"actions/ai/cover escape",
	"actions/ai/cover flags",
	"actions/ai/cover link",
	"actions/ai/cover lock",
	"actions/ai/cover type",
	"actions/ai/enable_melee_attacks",
	"actions/ai/follow",
	"actions/ai/force free",
	"actions/ai/lead",
	"actions/ai/lock_as_enemy",
	"actions/ai/lock_melee_attack",
	"actions/ai/melee/attack mask",
	"actions/ai/melee/enable attacks",
	"actions/ai/melee/lock as enemy",
	"actions/ai/melee/lock attack",
	"actions/ai/melee/stop attack",
	"actions/ai/melee_attack_mask",
	"actions/ai/monster face enemy",
	"actions/ai/move",
	"actions/ai/slowdown",
	"actions/ai/state",
	"actions/ai/static obstacle",
	"actions/ai/static_obstacle",
	"actions/ai/stop_melee_attack",
	"actions/ai/sun luminocity coef",
	"actions/ai/sun_lumin_coef",
	"actions/alert search enable",
	"actions/all_vision_params",
	"actions/allow attached move",
	"actions/allow_vr_vision",
	"actions/anim_movement",
	"actions/animated_gunmode",
	"actions/arm_seige_bomb",
	"actions/attach",
	"actions/attach hud to camera",
	"actions/attach to HUD",
	"actions/attach vs",
	"actions/attach with joint",
	"actions/attack_hit_shell",
	"actions/attraction",
	"actions/block breaking",
	"actions/block touch input",
	"actions/body state",
	"actions/break_ice",
	"actions/camera attach",
	"actions/cap_health",
	"actions/cct_settings",
	"actions/change ground holder",
	"actions/change map state",
	"actions/change_max_speed_vehicle",
	"actions/check_threat",
	"actions/clear_user",
	"actions/collision_group",
	"actions/common_combat",
	"actions/configure_vcamera",
	"actions/connect_vcamera",
	"actions/console command",
	"actions/console echo",
	"actions/cover flags",
	"actions/cover link",
	"actions/cover type",
	"actions/cover_combat",
	"actions/cover_task_params",
	"actions/destroy",
	"actions/destroy joint",
	"actions/destroy-keepsakes",
	"actions/detach",
	"actions/detach hud from camera",
	"actions/detach_all",
	"actions/disable_all_use",
	"actions/disable_flinch",
	"actions/disable_jumpover",
	"actions/disable_npc_collision",
	"actions/disable_player_melee_crit",
	"actions/disable_sliding",
	"actions/dynamite/animated throw",
	"actions/dynamite/throw",
	"actions/dynamite/throw_grenade",
	"actions/electric/power consumption control",
	"actions/electric/power off control",
	"actions/enemy_aggro",
	"actions/engine/3d_citadel_money_text",
	"actions/engine/3d_leaderboard",
	"actions/engine/3d_range",
	"actions/engine/3d_text",
	"actions/engine/achievement",
	"actions/engine/action cull distance",
	"actions/engine/append meshes",
	"actions/engine/apply tpreset",
	"actions/engine/aura mode",
	"actions/engine/auramode",
	"actions/engine/biom clone",
	"actions/engine/capture_video",
	"actions/engine/cast shadow",
	"actions/engine/check achievement",
	"actions/engine/check_achievement",
	"actions/engine/clone",
	"actions/engine/clone attaches",
	"actions/engine/clone multi",
	"actions/engine/clone_multi",
	"actions/engine/comm_marker",
	"actions/engine/configure_vcamera",
	"actions/engine/connect_vcamera",
	"actions/engine/console command",
	"actions/engine/console echo",
	"actions/engine/corsair/iCUE profile",
	"actions/engine/cut scene",
	"actions/engine/cut_scene",
	"actions/engine/device LED",
	"actions/engine/device_led",
	"actions/engine/disable photomode",
	"actions/engine/disable save",
	"actions/engine/disable_photomode",
	"actions/engine/disable_save",
	"actions/engine/discharge",
	"actions/engine/dlc",
	"actions/engine/end_cut_scene",
	"actions/engine/force env zone",
	"actions/engine/game news",
	"actions/engine/hints available",
	"actions/engine/icue_profile",
	"actions/engine/leaderboard",
	"actions/engine/light scale",
	"actions/engine/lightning",
	"actions/engine/make ghost",
	"actions/engine/make_ghost",
	"actions/engine/measure fps",
	"actions/engine/move2camera",
	"actions/engine/mp_info",
	"actions/engine/multiplayer info",
	"actions/engine/net-signal",
	"actions/engine/never sleeps",
	"actions/engine/neversleeps",
	"actions/engine/object texture",
	"actions/engine/outdoor sector",
	"actions/engine/pause",
	"actions/engine/play hud particles",
	"actions/engine/play video",
	"actions/engine/play_hud_particles",
	"actions/engine/portal throughput",
	"actions/engine/presence",
	"actions/engine/presence_context",
	"actions/engine/progress achievement",
	"actions/engine/progress_achievement",
	"actions/engine/property",
	"actions/engine/property_bit",
	"actions/engine/quick_load",
	"actions/engine/quick_save",
	"actions/engine/remove meshes",
	"actions/engine/replace model",
	"actions/engine/replace tpreset",
	"actions/engine/scale",
	"actions/engine/scene_hud",
	"actions/engine/screen texture",
	"actions/engine/sector visible",
	"actions/engine/set background music",
	"actions/engine/set env cubemap",
	"actions/engine/set env layer",
	"actions/engine/set environment",
	"actions/engine/set texture aux",
	"actions/engine/set weather",
	"actions/engine/set_texture_aux",
	"actions/engine/set_weather",
	"actions/engine/shadowcast",
	"actions/engine/show death menu",
	"actions/engine/show menu",
	"actions/engine/show_death_menu",
	"actions/engine/show_menu",
	"actions/engine/signal",
	"actions/engine/slowmo",
	"actions/engine/start_cut_scene",
	"actions/engine/steam_store",
	"actions/engine/stop hud particles",
	"actions/engine/stop_hud_particles",
	"actions/engine/swap model",
	"actions/engine/team_marker",
	"actions/engine/text_hud",
	"actions/engine/text_hud_ind",
	"actions/engine/text_hud_multi",
	"actions/engine/texture prestream",
	"actions/engine/view distance",
	"actions/engine/view entity",
	"actions/engine/volume",
	"actions/engine/vr_menu_input",
	"actions/engine/water blend",
	"actions/engine/water move",
	"actions/engine/water ripples mode",
	"actions/engine/weapon_price",
	"actions/engine/wipe hud particles",
	"actions/engine/wipe_hud_particles",
	"actions/entity/action_aux_prop",
	"actions/entity/add gesture",
	"actions/entity/anim param",
	"actions/entity/arm seige bomb",
	"actions/entity/attach",
	"actions/entity/attach to HUD",
	"actions/entity/attach vs",
	"actions/entity/attach with joint",
	"actions/entity/aux prop",
	"actions/entity/blink",
	"actions/entity/break ice",
	"actions/entity/clear user",
	"actions/entity/death protection",
	"actions/entity/destroy",
	"actions/entity/destroy joint",
	"actions/entity/destroy keepsakes",
	"actions/entity/detach",
	"actions/entity/detach all",
	"actions/entity/explode",
	"actions/entity/foliage push",
	"actions/entity/hit",
	"actions/entity/hud item controller",
	"actions/entity/hud_collision",
	"actions/entity/interest info",
	"actions/entity/interest_info",
	"actions/entity/model track",
	"actions/entity/model_track",
	"actions/entity/motion subst",
	"actions/entity/motion_subst",
	"actions/entity/move",
	"actions/entity/move project",
	"actions/entity/move restore",
	"actions/entity/move_restore",
	"actions/entity/move2cover",
	"actions/entity/mute sound",
	"actions/entity/override-material",
	"actions/entity/play/coloranim",
	"actions/entity/play/modifier",
	"actions/entity/play/motion",
	"actions/entity/play/motion control",
	"actions/entity/play/motion control CHEAT",
	"actions/entity/play/motion ex",
	"actions/entity/play/particles",
	"actions/entity/play/particles color",
	"actions/entity/play/particles color blend",
	"actions/entity/play/particles ex",
	"actions/entity/play/sound",
	"actions/entity/play/sound ex",
	"actions/entity/play/sound ex control",
	"actions/entity/set aux value",
	"actions/entity/set aux value ex",
	"actions/entity/set dao value",
	"actions/entity/set health",
	"actions/entity/set name",
	"actions/entity/shadowed",
	"actions/entity/show bone",
	"actions/entity/show hitmark",
	"actions/entity/stretchy man",
	"actions/entity/turn ladder",
	"actions/entity/turn light",
	"actions/entity/useful for player",
	"actions/entity/VR/real_world_lock",
	"actions/entity/VR/set_mech_offset",
	"actions/entity/VR/tracker_place",
	"actions/entity/wallmark",
	"actions/entity/waves emitter",
	"actions/entity/waves_emitter",
	"actions/entity/xz rotation mode",
	"actions/explode",
	"actions/ext/play_particles_ex",
	"actions/extinguish",
	"actions/fall",
	"actions/fallback",
	"actions/find_cover",
	"actions/finish_jumpover",
	"actions/forbid_aim",
	"actions/force actor state",
	"actions/force max rpm",
	"actions/force_field",
	"actions/force_free",
	"actions/force_sliding",
	"actions/freegun",
	"actions/game time/set time",
	"actions/game time/set time speed",
	"actions/game time/store time",
	"actions/game/narrative",
	"actions/game/ui/show hud menu",
	"actions/game/ui/show icon",
	"actions/game_time/set_time",
	"actions/game_time/set_time_speed",
	"actions/game_time/store_time",
	"actions/gasmask effect",
	"actions/gasmask hit",
	"actions/gasmask use tape",
	"actions/gasmask_spend_speed",
	"actions/gateway",
	"actions/goto_target",
	"actions/graph_path",
	"actions/headquarter",
	"actions/helper/counter control",
	"actions/hide mode",
	"actions/hint",
	"actions/hit",
	"actions/howl",
	"actions/hud item controller",
	"actions/hud/3D citadel_money text",
	"actions/hud/3D range",
	"actions/hud/3D text",
	"actions/hud/3d_leaderboard",
	"actions/hud/communication marker",
	"actions/hud/game news",
	"actions/hud/hints available",
	"actions/hud/scene hud",
	"actions/hud/team marker",
	"actions/hud/text",
	"actions/hud/text independent",
	"actions/hud/text multi",
	"actions/hud/vr/menu_input",
	"actions/hud/weapon price",
	"actions/human/action",
	"actions/human/active item",
	"actions/human/active_item",
	"actions/human/aim lag",
	"actions/human/aim_lag",
	"actions/human/allow weapon change",
	"actions/human/animated holder manager",
	"actions/human/animated_holder_mng",
	"actions/human/combat behaviour",
	"actions/human/combat cooldowns",
	"actions/human/combat_type",
	"actions/human/enable danger delta",
	"actions/human/enable panic",
	"actions/human/enable sniper",
	"actions/human/enable surrender",
	"actions/human/enable wounded combat",
	"actions/human/enable_surrender",
	"actions/human/fire shooting target",
	"actions/human/fire while moving",
	"actions/human/fire_shooting_target",
	"actions/human/fire_while_moving",
	"actions/human/melee only",
	"actions/human/neutral",
	"actions/human/property",
	"actions/human/set fire target",
	"actions/human/set speech name",
	"actions/human/set_fire_target",
	"actions/human/set_speech_name",
	"actions/human/suppress cover",
	"actions/human/surrender",
	"actions/human/swap holders",
	"actions/human/swap_holders",
	"actions/human/throw_grenade",
	"actions/human/weapon change",
	"actions/input generator",
	"actions/input_recording",
	"actions/input_recording",
	"actions/kinematic",
	"actions/lamp/shadowed",
	"actions/level/viewentity",
	"actions/light scale",
	"actions/link",
	"actions/logic/graph path",
	"actions/long idle",
	"actions/luminocity",
	"actions/make friend",
	"actions/make immortal",
	"actions/make invul",
	"actions/make scripted",
	"actions/make stunned",
	"actions/map_text",
	"actions/menu_mode",
	"actions/milestone",
	"actions/min mental state",
	"actions/monster/action_pathfind_collision",
	"actions/monster/aqua_female_sputum",
	"actions/monster/aqua_female_state",
	"actions/monster/aqua_male_mode",
	"actions/monster/aqua_male_unhide",
	"actions/monster/aqua_monster_mode",
	"actions/monster/aqua_monster_mode_new",
	"actions/monster/arahind_state",
	"actions/monster/arm gunner",
	"actions/monster/arm_gunner",
	"actions/monster/biomass_attack",
	"actions/monster/broadened_lian_attack",
	"actions/monster/change catfish depth",
	"actions/monster/change_catfish_depth",
	"actions/monster/creation fly",
	"actions/monster/creation_fly",
	"actions/monster/dark/anim_speed",
	"actions/monster/dark/make_angry",
	"actions/monster/demon_disable_attack",
	"actions/monster/demon_fly",
	"actions/monster/demon_ragdoll",
	"actions/monster/dog",
	"actions/monster/group_behaviour_allowed",
	"actions/monster/group_behaviour_params",
	"actions/monster/harpy/disable_attack",
	"actions/monster/harpy/fly",
	"actions/monster/harpy/ragdoll",
	"actions/monster/hit breakable",
	"actions/monster/hit_breakable",
	"actions/monster/monster_passive",
	"actions/monster/nosalis_female/action",
	"actions/monster/nosalis_female/anchor",
	"actions/monster/nosalis_female/sleep",
	"actions/monster/nosalis_female/state",
	"actions/monster/nosalis_female_action",
	"actions/monster/nosalis_female_anchor",
	"actions/monster/nosalis_female_sleep",
	"actions/monster/nosalis_female_state",
	"actions/monster/passive",
	"actions/monster/pathfind collision disable",
	"actions/monster/set gunner type",
	"actions/monster/set orient point",
	"actions/monster/set thrower type",
	"actions/monster/set_gunner_type",
	"actions/monster/set_librarian_aggro",
	"actions/monster/set_librarian_scripted_ex",
	"actions/monster/set_lurkers_state",
	"actions/monster/set_orient_point",
	"actions/monster/set_thrower_type",
	"actions/monster/snake_pursue",
	"actions/monster/snake_range_attack",
	"actions/monster/snake_reach_out",
	"actions/monster/watchman/dog",
	"actions/monster/watchman/get_reinforcements",
	"actions/monster/watchman/group_behaviour_mode",
	"actions/monster/watchman_get_reinforcements",
	"actions/monster/watchman_group_behaviour_mode",
	"actions/monster/worm/pursue",
	"actions/monster/worm/range_attack",
	"actions/monster/worm/reach out",
	"actions/mount gun",
	"actions/move",
	"actions/move project",
	"actions/move2cover",
	"actions/movement type",
	"actions/music/play theme",
	"actions/music/set scheme",
	"actions/music/stop",
	"actions/mute sound",
	"actions/net/action_objective_complete",
	"actions/net/activate_hq",
	"actions/net/change_team",
	"actions/net/change_teams",
	"actions/net/check class",
	"actions/net/check class multi",
	"actions/net/check team",
	"actions/net/check_class",
	"actions/net/check_class_multi",
	"actions/net/check_prop",
	"actions/net/check_team",
	"actions/net/check_teams",
	"actions/net/check_teams_ex",
	"actions/net/check_teams_prop",
	"actions/net/make ready",
	"actions/net/make_ready",
	"actions/net/money_back",
	"actions/net/net_prop",
	"actions/net/net_prop_bit",
	"actions/net/net_prop_bit_players",
	"actions/net/net_prop_players",
	"actions/net/respawn",
	"actions/net/respawn_ex",
	"actions/net/respawn_multi",
	"actions/net/save_player_stats",
	"actions/net/set activity",
	"actions/net/set class",
	"actions/net/set team",
	"actions/net/set_class",
	"actions/net/set_mp_activity",
	"actions/net/team_prop",
	"actions/net/team_prop_bit",
	"actions/net/team_prop2",
	"actions/net/team_prop2_bit",
	"actions/net/ui clone",
	"actions/net/ui_clone",
	"actions/net/zone_prop",
	"actions/net-player/bit",
	"actions/net-player/bit players",
	"actions/net-player/prop",
	"actions/net-player/prop players",
	"actions/net-player/save stats",
	"actions/net-player/zone_prop",
	"actions/net-team/bit",
	"actions/net-team/change teams",
	"actions/net-team/check prop",
	"actions/net-team/check teams",
	"actions/net-team/check teams ex",
	"actions/net-team/money back",
	"actions/net-team/prop",
	"actions/net-team/prop2",
	"actions/net-team/prop2 bit",
	"actions/no_combat",
	"actions/non npc static obstacle",
	"actions/nonnpc_obstacle",
	"actions/npc can play motion",
	"actions/npc grenade",
	"actions/npc/action feelings",
	"actions/npc/alert search enable",
	"actions/npc/all vision params",
	"actions/npc/allow attached move",
	"actions/npc/anim state",
	"actions/npc/anim_speed",
	"actions/npc/animated_gunmode",
	"actions/npc/auto interest group",
	"actions/npc/biomass_attack",
	"actions/npc/block ai vision",
	"actions/npc/body state",
	"actions/npc/broadened_lian_attack",
	"actions/npc/can be group leader",
	"actions/npc/can play motion",
	"actions/npc/cancel vs",
	"actions/npc/cancel_vs",
	"actions/npc/change voice",
	"actions/npc/check movement",
	"actions/npc/check threat",
	"actions/npc/check_movement",
	"actions/npc/choose priority target",
	"actions/npc/choose_priority_target",
	"actions/npc/common combat",
	"actions/npc/cover anchor",
	"actions/npc/cover combat",
	"actions/npc/cover group",
	"actions/npc/cover task params",
	"actions/npc/damage handle preset",
	"actions/npc/dark_make_angry",
	"actions/npc/disable flinch",
	"actions/npc/disable player melee crit",
	"actions/npc/dispersion",
	"actions/npc/dispersion_props",
	"actions/npc/enable scary",
	"actions/npc/enemy aggro",
	"actions/npc/fall",
	"actions/npc/fallback",
	"actions/npc/find cover",
	"actions/npc/flinch_clear",
	"actions/npc/forbid melee kill",
	"actions/npc/forbid_melee_kill",
	"actions/npc/force max rpm",
	"actions/npc/force ragdoll death",
	"actions/npc/force_ragdoll_death",
	"actions/npc/free2go",
	"actions/npc/free2go group",
	"actions/npc/freegun",
	"actions/npc/gasmask voice",
	"actions/npc/gasmask_voice",
	"actions/npc/get group leader",
	"actions/npc/goto target",
	"actions/npc/group",
	"actions/npc/group leader",
	"actions/npc/groups members",
	"actions/npc/hide mode",
	"actions/npc/hit power",
	"actions/npc/hit_power",
	"actions/npc/howl",
	"actions/npc/illuminated react level",
	"actions/npc/illuminated_react_level",
	"actions/npc/immunities",
	"actions/npc/lock VS",
	"actions/npc/lock VS block",
	"actions/npc/lock_vs",
	"actions/npc/lock_vs_block",
	"actions/npc/luminocity",
	"actions/npc/luminocity correction",
	"actions/npc/make friend",
	"actions/npc/make scripted",
	"actions/npc/make/immortal",
	"actions/npc/make/invulnerable",
	"actions/npc/make/stunned",
	"actions/npc/movement type",
	"actions/npc/no combat",
	"actions/npc/npc grenadier",
	"actions/npc/obstacle",
	"actions/npc/one shot",
	"actions/npc/open fire",
	"actions/npc/pathfind check",
	"actions/npc/pfnn state",
	"actions/npc/play cover path",
	"actions/npc/play cover path ex",
	"actions/npc/play delta",
	"actions/npc/play dialog",
	"actions/npc/play path",
	"actions/npc/play patrol path",
	"actions/npc/queue params",
	"actions/npc/register motion sensor",
	"actions/npc/register_motion_sensor",
	"actions/npc/reload",
	"actions/npc/remove from level mental",
	"actions/npc/remove_from_lvl_mental",
	"actions/npc/restrictor_block_ai_vision",
	"actions/npc/scripted fire",
	"actions/npc/set enemy",
	"actions/npc/set group leader",
	"actions/npc/set hide cover",
	"actions/npc/set hit preset",
	"actions/npc/set interest mode",
	"actions/npc/set priority target flag",
	"actions/npc/set sound schema",
	"actions/npc/set turn options",
	"actions/npc/set_hide_cover",
	"actions/npc/set_priority_target",
	"actions/npc/skip crosshair test",
	"actions/npc/skip stick to ai map",
	"actions/npc/smell",
	"actions/npc/sound params",
	"actions/npc/species behavior",
	"actions/npc/speech groups",
	"actions/npc/static combat",
	"actions/npc/static combat anchor",
	"actions/npc/stick to ground",
	"actions/npc/stick_to_ground",
	"actions/npc/take cover",
	"actions/npc/threat params",
	"actions/npc/unlock cover",
	"actions/npc/unreachable enemy anchor",
	"actions/npc/update ik",
	"actions/npc/visible_for_NPC",
	"actions/npc/vision params",
	"actions/npc/vs_move",
	"actions/npc/wounded",
	"actions/npc/wounded_params",
	"actions/nvidia highlighted",
	"actions/nvidia highlights get summary",
	"actions/nvidia_highlighted",
	"actions/nvidia_highlights_get_summary",
	"actions/object_texture",
	"actions/one shot",
	"actions/open fire",
	"actions/park_vehicle",
	"actions/particles color",
	"actions/particles color blend",
	"actions/pathfind_check",
	"actions/pfnn state",
	"actions/p-force",
	"actions/physics/attack hit shell",
	"actions/physics/attraction",
	"actions/physics/cct_settings",
	"actions/physics/collision_group",
	"actions/physics/disable jumpover",
	"actions/physics/disable sliding",
	"actions/physics/disable_npc_collision",
	"actions/physics/finish jumpover",
	"actions/physics/force sliding",
	"actions/physics/force_field",
	"actions/physics/park vehicle",
	"actions/physics/p-force",
	"actions/physics/physx boat/change max speed",
	"actions/physics/physx vehicle/engine",
	"actions/physics/set physics props",
	"actions/physics/simple_cct",
	"actions/physics/slope_settings",
	"actions/physics/stop vehicle",
	"actions/physx_vehicle",
	"actions/platform_attach",
	"actions/platform_deattach",
	"actions/play animation",
	"actions/play camera-effect",
	"actions/play color cube",
	"actions/play coloranim",
	"actions/play cover path",
	"actions/play cover path ex",
	"actions/play dialog",
	"actions/play face idle",
	"actions/play modifier",
	"actions/play motion",
	"actions/play motion control",
	"actions/play motion control ch",
	"actions/play motion ex",
	"actions/play music theme",
	"actions/play particles",
	"actions/play path",
	"actions/play patrol path",
	"actions/play sound",
	"actions/play sound ex",
	"actions/play sound ex control",
	"actions/play vibration",
	"actions/play vibration VR",
	"actions/play_face_idle",
	"actions/player/action slot",
	"actions/player/activate restrictor",
	"actions/player/active_slot",
	"actions/player/ammo restriction",
	"actions/player/ammo_restriction",
	"actions/player/anim movement",
	"actions/player/attach camera",
	"actions/player/camera axis lock",
	"actions/player/camera spring mode",
	"actions/player/change map state",
	"actions/player/charger control",
	"actions/player/charger voltage",
	"actions/player/charger_control",
	"actions/player/charger_voltage",
	"actions/player/check slot",
	"actions/player/citadel_money",
	"actions/player/civil mode",
	"actions/player/clear discovered weapon",
	"actions/player/clear_discovered_wpn",
	"actions/player/crouch",
	"actions/player/data/add",
	"actions/player/data/check",
	"actions/player/data/remove",
	"actions/player/disable all use",
	"actions/player/disable apply state",
	"actions/player/disable camera sync",
	"actions/player/disable craft",
	"actions/player/disable sprint track",
	"actions/player/disable upgrade",
	"actions/player/disable visibility marker",
	"actions/player/disable_apply_state",
	"actions/player/disable_camera_sync",
	"actions/player/disable_craft",
	"actions/player/doctor",
	"actions/player/effect switcher",
	"actions/player/fastdrop switcher",
	"actions/player/filters_spend",
	"actions/player/footprint",
	"actions/player/forbid aim",
	"actions/player/forbid backpack slots",
	"actions/player/forbid_backpack_slots",
	"actions/player/friend_mode",
	"actions/player/friend_mode_target",
	"actions/player/gasmask control",
	"actions/player/gasmask effect",
	"actions/player/gasmask filter limits",
	"actions/player/gasmask hit",
	"actions/player/gasmask spend speed",
	"actions/player/gasmask use tape",
	"actions/player/give ammo",
	"actions/player/give_ammo",
	"actions/player/grenade timeouts",
	"actions/player/grenade_timeouts",
	"actions/player/hands hide",
	"actions/player/hands show",
	"actions/player/head_delta",
	"actions/player/hide hands",
	"actions/player/hide subj",
	"actions/player/holster",
	"actions/player/hud_anim_speed",
	"actions/player/in combat",
	"actions/player/in flames",
	"actions/player/in_combat",
	"actions/player/input_generator",
	"actions/player/level map mark",
	"actions/player/lock camera",
	"actions/player/long idle",
	"actions/player/luminocity correction",
	"actions/player/map text",
	"actions/player/metal detector object",
	"actions/player/metal detector object reg",
	"actions/player/mount vehicle",
	"actions/player/mount_vehicle",
	"actions/player/movement",
	"actions/player/movement allowed",
	"actions/player/movement ex",
	"actions/player/platform_attach",
	"actions/player/platform_detach",
	"actions/player/play camera-effect",
	"actions/player/play dof",
	"actions/player/play vibration",
	"actions/player/play_hud_anim",
	"actions/player/player lean",
	"actions/player/points/add",
	"actions/player/points/check",
	"actions/player/points/reset",
	"actions/player/power_off_control",
	"actions/player/property",
	"actions/player/property bit",
	"actions/player/purge ammo",
	"actions/player/purge_ammo",
	"actions/player/random controls",
	"actions/player/restrictor obstacle",
	"actions/player/restrictor_activate",
	"actions/player/restrictor_obstacle",
	"actions/player/savepos",
	"actions/player/set ammo",
	"actions/player/set_ammo",
	"actions/player/show crosshair",
	"actions/player/show hands",
	"actions/player/show subj",
	"actions/player/slot restriction",
	"actions/player/slot_restriction",
	"actions/player/slow stop",
	"actions/player/slowmo",
	"actions/player/spend ammo",
	"actions/player/spend_ammo",
	"actions/player/stamina",
	"actions/player/start timer",
	"actions/player/subj hide",
	"actions/player/subj show",
	"actions/player/torchlight disturb distance",
	"actions/player/torchlight_control",
	"actions/player/torchlight_disturb_distance",
	"actions/player/turn torchlight",
	"actions/player/unlimited ammo",
	"actions/player/visible hud",
	"actions/player/visible hud ui",
	"actions/player/visy/apply foliage",
	"actions/player/VR/allow vision",
	"actions/player/VR/block touch input",
	"actions/player/VR/play touch vibration",
	"actions/player/VR/virtual boundries",
	"actions/player/VR/virtual grab",
	"actions/player/way point",
	"actions/player/way_point",
	"actions/player/weapon breaking",
	"actions/player/weapon make dismantlable",
	"actions/player/weapon_breaking",
	"actions/player/weapon_down",
	"actions/player/wear binoculars",
	"actions/player/wear gasmask",
	"actions/player/wear nightvision",
	"actions/player/wear suit",
	"actions/progress item",
	"actions/queue params",
	"actions/request transition",
	"actions/request_transition",
	"actions/savepos",
	"actions/scound_schema",
	"actions/screen_texture",
	"actions/scripted fire",
	"actions/set enemy",
	"actions/set music scheme",
	"actions/set physics props",
	"actions/set_filters_spend",
	"actions/set_hit_preset",
	"actions/set_mech_offset",
	"actions/set_name",
	"actions/set_narrative",
	"actions/set_speech_groups",
	"actions/set_turn_options",
	"actions/show_diary",
	"actions/show_hints_menu",
	"actions/show_hitmark",
	"actions/show_hud_menu",
	"actions/show_icon",
	"actions/show_postcard",
	"actions/simple_cct",
	"actions/skeleton smooth",
	"actions/slope_settings",
	"actions/smell",
	"actions/sound params",
	"actions/species_behavior",
	"actions/start timer",
	"actions/static_combat",
	"actions/static_combat_anchor",
	"actions/stop music",
	"actions/stop_vehicle",
	"actions/stretchy_man",
	"actions/take_cover",
	"actions/terrain_decal_toggle",
	"actions/threat_params",
	"actions/toggle",
	"actions/trade action costume",
	"actions/treadmil",
	"actions/treadmill",
	"actions/turn ladder",
	"actions/turn light",
	"actions/turn torchlight",
	"actions/turret control",
	"actions/turret_control",
	"actions/ui/add_diary",
	"actions/ui/add_postcard",
	"actions/ui/control_visibility",
	"actions/ui/hint",
	"actions/ui/loader_diary_open",
	"actions/ui/menu control visibility",
	"actions/ui/menu mode",
	"actions/ui/progress item",
	"actions/ui/show_diary",
	"actions/ui/show_hints_menu",
	"actions/ui/show_postcard",
	"actions/ui/trade action costume",
	"actions/ui/trade action weapon",
	"actions/unlock_cover",
	"actions/update ik",
	"actions/update once",
	"actions/update_once",
	"actions/virtual boundries",
	"actions/virtual grab",
	"actions/vision params",
	"actions/voice",
	"actions/vs_move",
	"actions/water_blend",
	"actions/water_move",
	"actions/water_ripples_mode",
	"actions/weapon/dismantlable",
	"actions/weapon/dispersion",
	"actions/weapon/install upgrade",
	"actions/weapon/install_upgrade",
	"actions/weapon/laser control",
	"actions/weapon/pump",
	"actions/weapon/rocket_launch",
	"actions/weapon/set weapon items",
	"actions/weapon/set weapon pressure",
	"actions/weapon/VR/rocket launch",
	"actions/wear binoculars",
	"actions/wear gasmask",
	"actions/wear nightvision",
	"actions/wear_suit",
	"actions/xz rotation mode",
	"actions/zone type",
	"actions/zone/type",
	"checker/animation",
	"checker/AUX",
	"checker/build_key",
	"checker/compare ammo",
	"checker/compare_ammo",
	"checker/demo_mode",
	"checker/dlc",
	"checker/entity/bone inside",
	"checker/entity/check targets count",
	"checker/entity/compare distance",
	"checker/entity/compare_distance",
	"checker/entity/has refs",
	"checker/entity/height",
	"checker/entity/is between",
	"checker/entity/is same",
	"checker/entity/is_between",
	"checker/entity/is_same",
	"checker/entity/last_in_zone",
	"checker/entity/state",
	"checker/entity/velocity",
	"checker/entity/visible",
	"checker/entity/visible for NPC",
	"checker/entity/visible4npc",
	"checker/game time/check time",
	"checker/game_plus/can_start",
	"checker/game_plus/started",
	"checker/game_time/check_time",
	"checker/gamepad",
	"checker/hit preset",
	"checker/hit_preset",
	"checker/level",
	"checker/localizable_signs",
	"checker/model",
	"checker/monster/",
	"checker/monster/airborne",
	"checker/monster/arahind upside",
	"checker/mutations",
	"checker/net/peer",
	"checker/NG+/can start",
	"checker/NG+/mutations",
	"checker/NG+/started",
	"checker/np/trophy",
	"checker/npc/can standup",
	"checker/npc/can_standup",
	"checker/npc/enemy",
	"checker/npc/has enemy",
	"checker/npc/has_enemy",
	"checker/npc/is group leader",
	"checker/npc/is_group_leader",
	"checker/npc/is_npc_type",
	"checker/npc/movement interrupt",
	"checker/npc/movement_interrupt",
	"checker/npc/overlap test",
	"checker/npc/overlap_test",
	"checker/npc/pc_type",
	"checker/npc/speech group",
	"checker/npc/speech_group",
	"checker/npc/surrender",
	"checker/npc/threat dist",
	"checker/npc/threat_dist",
	"checker/npc/type",
	"checker/patch-dlc",
	"checker/platform",
	"checker/player/can melee",
	"checker/player/costume upgrade enabled",
	"checker/player/item active",
	"checker/player/popup allowed",
	"checker/qte mode",
	"checker/qte_mode",
	"checker/rt_demo",
	"checker/thq_connect",
	"checker/weapon/has weapon items",
	"checker/xbox_live",
	"chooser/random",
	"covers/best",
	"covers/best_cover_ref",
	"covers/cover_by_eval",
	"covers/covers name",
	"covers/invisible",
	"covers/name",
	"covers/ref",
	"empty",
	"empty_not_delta",
	"entities/active weapon",
	"entities/arm device ref",
	"entities/children",
	"entities/dialog's actor",
	"entities/entity children",
	"entities/entity dialog's actor",
	"entities/entity hud ref",
	"entities/entity inv item",
	"entities/entity invisible",
	"entities/entity kulemet",
	"entities/entity kulemet hands",
	"entities/entity labeled",
	"entities/entity level player",
	"entities/entity name",
	"entities/entity parent",
	"entities/entity player",
	"entities/entity player self",
	"entities/entity player's hands",
	"entities/entity player's heap",
	"entities/entity player's knife",
	"entities/entity player's timer",
	"entities/entity player's torch",
	"entities/entity ref",
	"entities/entity rucksack item",
	"entities/entity self",
	"entities/entity self not player",
	"entities/entity trade weapon",
	"entities/entity user",
	"entities/entity wpn attach",
	"entities/filters/enemies filter",
	"entities/filters/friend filter",
	"entities/filters/is alive filter",
	"entities/filters/is npc filter",
	"entities/filters/nearest item",
	"entities/filters/npc group filter",
	"entities/filters/npc type filter",
	"entities/filters/priority targets filter",
	"entities/filters/weapon types filter",
	"entities/groups members",
	"entities/inventory item",
	"entities/invisible",
	"entities/killer",
	"entities/killer",
	"entities/kulemet",
	"entities/kulemet hands",
	"entities/labeled",
	"entities/metal detector target",
	"entities/monster enemy",
	"entities/monster_enemy",
	"entities/movement pusher",
	"entities/movement_hitter",
	"entities/mp group enemy",
	"entities/mp_group_enemy",
	"entities/name",
	"entities/npc enemy",
	"entities/npc enemy ex",
	"entities/npc_enemy",
	"entities/npc_enemy_ex",
	"entities/parent",
	"entities/player",
	"entities/player enemy",
	"entities/player enemy mp",
	"entities/player on start",
	"entities/player self",
	"entities/player_enemy",
	"entities/player_enemy_mp",
	"entities/player's hands",
	"entities/player's heap",
	"entities/player's knife",
	"entities/player's timer",
	"entities/player's torch",
	"entities/pose attp ref",
	"entities/pose weapon locator ref",
	"entities/ref",
	"entities/rucksack item",
	"entities/self",
	"entities/self not player",
	"entities/target_npc",
	"entities/trade weapon",
	"entities/upgrade arm device ref",
	"entities/user",
	"entities/visible for NPC",
	"filter/bone_filter",
	"filter/bone_part",
	"fun/set boss",
	"fun/text splash",
	"logic/adv/and-2-ext",
	"logic/adv/counter ref no touch",
	"logic/adv/random_selector_2",
	"logic/adv/randomex",
	"logic/adv/randomex-2",
	"logic/adv/randomex-3",
	"logic/adv/randomex-4",
	"logic/adv/randomex-5",
	"logic/ai/cover/dirrandom",
	"logic/ai/cover/escape",
	"logic/ai/cover/hide",
	"logic/ai/cover/in direction",
	"logic/ai/cover/invisible enemygroup",
	"logic/ai/cover/mp/dm",
	"logic/ai/cover/mp/equidistant",
	"logic/ai/cover/mp/far",
	"logic/ai/cover/mp/near",
	"logic/ai/cover/near enemy",
	"logic/ai/cover/near player",
	"logic/ai/cover/nearest",
	"logic/ai/cover/random",
	"logic/and-2",
	"logic/and-3",
	"logic/and-multi",
	"logic/BOOL OPS/and-2",
	"logic/BOOL OPS/and-3",
	"logic/BOOL OPS/and-multi",
	"logic/BOOL OPS/or-2",
	"logic/BOOL OPS/or-3",
	"logic/BOOL OPS/or-multi",
	"logic/BOOL OPS/xor-2",
	"logic/BOOL OPS/xor-3",
	"logic/chooser",
	"logic/counter",
	"logic/counter ref",
	"logic/counter sel",
	"logic/counter/counter",
	"logic/counter/ref",
	"logic/counter/sel",
	"logic/delay",
	"logic/delay ex",
	"logic/delay hq",
	"logic/delay hq ex",
	"logic/delay hud",
	"logic/delay multi",
	"logic/exposed_locker",
	"logic/graph path",
	"logic/hub",
	"logic/locker",
	"logic/locker_base",
	"logic/lockers/easy",
	"logic/lockers/heavy",
	"logic/or-2",
	"logic/or-3",
	"logic/or-multi",
	"logic/random",
	"logic/random/random",
	"logic/random/random-chooser",
	"logic/random/randomex",
	"logic/random-2",
	"logic/random-3",
	"logic/random-4",
	"logic/random-5",
	"logic/random-chooser",
	"logic/random-chooser-2",
	"logic/random-chooser-3",
	"logic/random-chooser-4",
	"logic/random-chooser-5",
	"logic/select/2",
	"logic/select/3",
	"logic/select/4",
	"logic/select/5",
	"logic/select/select",
	"logic/select_param",
	"logic/select-2",
	"logic/select-3",
	"logic/select-4",
	"logic/select-5",
	"logic/switch/2",
	"logic/switch/3",
	"logic/switch/4",
	"logic/switch/5",
	"logic/switch/switch",
	"logic/switch/switchboard",
	"logic/switch_param",
	"logic/switch-2",
	"logic/switch-3",
	"logic/switch-4",
	"logic/switch-5",
	"logic/switchboard",
	"logic/xor-2",
	"logic/xor-3",
	"process/add",
	"process/blender",
	"process/blender_match_events",
	"process/blender_phased",
	"process/bone part",
	"process/double",
	"process/filter",
	"process/fixed blender",
	"process/fixed_blender",
	"process/gesture redirect",
	"process/gesture_blender",
	"process/gesture_redirect",
	"process/IKs",
	"process/multi blender",
	"process/multi_blender",
	"process/replace",
	"process/replace with IKs",
	"process/signal blender",
	"process/signal_blender",
	"source/cover motion",
	"source/cover_motion",
	"source/FaceFX motion",
	"source/facefx_motion",
	"source/gesture motion",
	"source/gesture_motion",
	"source/motion",
	"source/param motion",
	"source/param_motion",
	"source/pausable motion",
	"source/pausable_motion",
	"source/PFNN motion",
	"source/pfnn_motion",
	"source/physics",
	"source/signal motion",
	"source/signal_motion",
	"source/subst motion",
	"source/subst_motion",
	"state/detached state",
	"state/dg transition",
	"state/dg_transition",
	"state/lock movement",
	"state/lock_movement",
	"state/locomotion state",
	"state/param time transition",
	"state/param_transition",
	"state/placeholder",
	"state/random transition",
	"state/random_transition",
	"state/redir",
	"state/ref",
	"state/state",
	"state/transition",
	"state/transition_match_events",
	"trade/bullet exchange",
	"trade/deal",
	"trade/dismantle weapon",
	"trade/get player gold",
	"trade/purge slot",
	"trade/take item",
	"trade/test my weapon",
	"trade/trade trigger",
	"trigger/ai map clamping",
	"trigger/ai map leaving",
	"trigger/ammo spend",
	"trigger/corpse",
	"trigger/cover locking",
	"trigger/did install upgrade",
	"trigger/group leader dead",
	"trigger/has ammo",
	"trigger/has fast drop",
	"trigger/hearing",
	"trigger/metal_detected",
	"trigger/pick up ammo",
	"trigger/pick up fastdrop",
	"trigger/pick up upgrade",
	"trigger/pick up weapon",
	"trigger/ragdoll",
	"trigger/vision",
	"triggers/active item",
	"triggers/active_state",
	"triggers/aftercloned",
	"triggers/ai/cover invalid",
	"triggers/ai/ext/precond checker",
	"triggers/ai/precond checker",
	"triggers/ai_map_material",
	"triggers/alert_search",
	"triggers/am i enemy",
	"triggers/ameba zombie",
	"triggers/ameba_die",
	"triggers/ammo absent",
	"triggers/ammo_ready",
	"triggers/anim event",
	"triggers/anim param",
	"triggers/anim signal",
	"triggers/any player",
	"triggers/any_input",
	"triggers/any_player_special",
	"triggers/aqua female",
	"triggers/aqua male",
	"triggers/arahind state",
	"triggers/attach-detach",
	"triggers/auto interest",
	"triggers/auto_save_info",
	"triggers/binoculars",
	"triggers/body_posture",
	"triggers/camera-track event",
	"triggers/change difficult",
	"triggers/charger",
	"triggers/close_range weapon",
	"triggers/collision",
	"triggers/continue_no_available",
	"triggers/credits_finished",
	"triggers/ctf",
	"triggers/curve_shot",
	"triggers/danger_activity",
	"triggers/debug/input",
	"triggers/debug_input",
	"triggers/dialog begin or end",
	"triggers/dialog start",
	"triggers/dialog/dialog start",
	"triggers/dialog/mouse interest",
	"triggers/die",
	"triggers/dog_smell",
	"triggers/engine/achievement",
	"triggers/engine/mic threshold",
	"triggers/engine/property_bit",
	"triggers/engine/signal",
	"triggers/engine/speech_client",
	"triggers/engine/speech_recognized offline",
	"triggers/engine/speech_recognized online",
	"triggers/entity/after cloned",
	"triggers/entity/ameba_die",
	"triggers/entity/anim param",
	"triggers/entity/attach-detach",
	"triggers/entity/collision",
	"triggers/entity/curve shot",
	"triggers/entity/die",
	"triggers/entity/facefx event",
	"triggers/entity/health threshold",
	"triggers/entity/health threshold2",
	"triggers/entity/hit",
	"triggers/entity/hit ref",
	"triggers/entity/lamp die",
	"triggers/entity/look at",
	"triggers/entity/move",
	"triggers/entity/orientation",
	"triggers/entity/phys bottom reached",
	"triggers/entity/use",
	"triggers/entity/use bomb",
	"triggers/entity/use multiimage",
	"triggers/entity/velocity",
	"triggers/entity/web burn",
	"triggers/event/anim",
	"triggers/event/anim signal",
	"triggers/event/camera-track",
	"triggers/event/danger activity",
	"triggers/facefx event",
	"triggers/fastdrop/throwing",
	"triggers/filters_time_spend",
	"triggers/game time/time event",
	"triggers/game/achievement",
	"triggers/game/any input",
	"triggers/game/auto save info",
	"triggers/game/continue no available",
	"triggers/game/coop person trigger",
	"triggers/game/credits finished",
	"triggers/game/difficulty change",
	"triggers/game/difficulty check",
	"triggers/game/game mode",
	"triggers/game/gamepad",
	"triggers/game/gameplay achievement",
	"triggers/game/gameplay_achievement",
	"triggers/game/level mental",
	"triggers/game/load no available",
	"triggers/game/loaded",
	"triggers/game/loading screen",
	"triggers/game/main_menu",
	"triggers/game/menu dpad trigger",
	"triggers/game/menu trigger",
	"triggers/game/navi trigger",
	"triggers/game/navi trigger use",
	"triggers/game/navi use trigger",
	"triggers/game/next level",
	"triggers/game/play video",
	"triggers/game/player wpn collision",
	"triggers/game/player_weapon_collision",
	"triggers/game/ranger mode",
	"triggers/game/spectator cameras",
	"triggers/game/spectator trigger",
	"triggers/game/start",
	"triggers/game/stop video",
	"triggers/game/survival mode check",
	"triggers/game/take cover",
	"triggers/game/take_cover",
	"triggers/game/time in game",
	"triggers/game/ui/dpad menu",
	"triggers/game/ui/menu trigger",
	"triggers/game/weapon hit",
	"triggers/game/weapon state",
	"triggers/game/weapon_hit",
	"triggers/game/weapon_state",
	"triggers/game_difficulty",
	"triggers/game_difficulty_change",
	"triggers/game_mode",
	"triggers/game_stats/custom event",
	"triggers/game_stats/spawn",
	"triggers/game_stats/start_game",
	"triggers/game_stats/win_game",
	"triggers/game_survival_mode",
	"triggers/game_time/time_event",
	"triggers/gameloaded",
	"triggers/gamepad",
	"triggers/gamepad_input",
	"triggers/gasmask",
	"triggers/gasmask clear",
	"triggers/gasmask_ex",
	"triggers/generic",
	"triggers/generic_special",
	"triggers/generic-no-player",
	"triggers/gold_saved",
	"triggers/gold_spend",
	"triggers/grenade thrown",
	"triggers/grenade_is_close",
	"triggers/group role",
	"triggers/has_target",
	"triggers/heap",
	"triggers/helpers/counter trigger",
	"triggers/hit",
	"triggers/hit ref",
	"triggers/hq",
	"triggers/illuminated",
	"triggers/illumination",
	"triggers/in flames",
	"triggers/input",
	"triggers/interest",
	"triggers/is fire",
	"triggers/is god mode",
	"triggers/is milestone",
	"triggers/is player busy",
	"triggers/ladder",
	"triggers/lamp_die",
	"triggers/level_mental",
	"triggers/lian_state",
	"triggers/load_no_available",
	"triggers/loading_screen",
	"triggers/low ammo",
	"triggers/main menu",
	"triggers/mech_vr_pull",
	"triggers/medkit",
	"triggers/menu activated",
	"triggers/menu button",
	"triggers/menu event",
	"triggers/menu/activated",
	"triggers/menu/button clicked",
	"triggers/menu/input",
	"triggers/menu/menu event",
	"triggers/mic threshold",
	"triggers/money",
	"triggers/monster/aqua female",
	"triggers/monster/aqua male",
	"triggers/monster/arahind state",
	"triggers/monster/group role",
	"triggers/monster/lian state",
	"triggers/monster/librarian state",
	"triggers/monster/watchman group",
	"triggers/mouse interest",
	"triggers/movement dir",
	"triggers/movement hit",
	"triggers/net/base_used",
	"triggers/net/best player",
	"triggers/net/best_player",
	"triggers/net/check_prop",
	"triggers/net/check_prop_bit",
	"triggers/net/check_prop_multi",
	"triggers/net/die assist",
	"triggers/net/log_custom_event",
	"triggers/net/log_spawn",
	"triggers/net/log_start_game",
	"triggers/net/log_win_game",
	"triggers/net/mp/avenger",
	"triggers/net/mp/nemesis",
	"triggers/net/mp/payback",
	"triggers/net/mp/saviour",
	"triggers/net/net_signin",
	"triggers/net/signin",
	"triggers/net/state",
	"triggers/net/team_prop",
	"triggers/net/team_prop_bit",
	"triggers/net/team_size",
	"triggers/net/vote",
	"triggers/net/xbox_session",
	"triggers/net-player/bit",
	"triggers/net-player/prop",
	"triggers/net-player/prop multi",
	"triggers/net-team/bit",
	"triggers/net-team/prop",
	"triggers/net-team/size",
	"triggers/nextlevel",
	"triggers/nightvision",
	"triggers/nightvision_added",
	"triggers/npc",
	"triggers/npc enemy",
	"triggers/npc enemy is close",
	"triggers/npc mental state",
	"triggers/npc threat",
	"triggers/npc/active state",
	"triggers/npc/ai map clamping",
	"triggers/npc/ai map leaving",
	"triggers/npc/ai map material",
	"triggers/npc/alert search",
	"triggers/npc/am i enemy",
	"triggers/npc/ameba zombie",
	"triggers/npc/ammo spend",
	"triggers/npc/auto interest",
	"triggers/npc/body posture",
	"triggers/npc/close-range weapon",
	"triggers/npc/cover locking",
	"triggers/npc/dialog begin or end",
	"triggers/npc/die from",
	"triggers/npc/dog smell",
	"triggers/npc/enemy",
	"triggers/npc/enemy is close",
	"triggers/npc/feel/corpse",
	"triggers/npc/feel/hearing",
	"triggers/npc/feel/vision",
	"triggers/npc/grenade is close",
	"triggers/npc/grenade thrown",
	"triggers/npc/group leader dead",
	"triggers/npc/illuminated by player",
	"triggers/npc/illumination",
	"triggers/npc/mental state",
	"triggers/npc/mood",
	"triggers/npc/movement dir",
	"triggers/npc/movement hit",
	"triggers/npc/npc in cover",
	"triggers/npc/pass cover",
	"triggers/npc/pathfind target",
	"triggers/npc/pinned",
	"triggers/npc/ragdoll",
	"triggers/npc/smell",
	"triggers/npc/taran",
	"triggers/npc/threat",
	"triggers/npc/threat_orientation",
	"triggers/npc/weapon active state",
	"triggers/npc/wounded",
	"triggers/npc/zombie",
	"triggers/npc_die_from",
	"triggers/npc_in_cover",
	"triggers/npc_mood",
	"triggers/object",
	"triggers/object_is_close",
	"triggers/on use",
	"triggers/open backpack",
	"triggers/out of filters",
	"triggers/pass cover",
	"triggers/pathfind enemy",
	"triggers/photo mode",
	"triggers/phys_bottom_reached",
	"triggers/pinned",
	"triggers/player",
	"triggers/player can lean",
	"triggers/player die",
	"triggers/player in combat",
	"triggers/player jumpon",
	"triggers/player jumpover",
	"triggers/player map",
	"triggers/player on ai map",
	"triggers/player sliding",
	"triggers/player stamina",
	"triggers/player/active item",
	"triggers/player/alt ammo ready",
	"triggers/player/ammo absent",
	"triggers/player/binoculars",
	"triggers/player/charger",
	"triggers/player/filters time spend",
	"triggers/player/gasmask",
	"triggers/player/gasmask clear",
	"triggers/player/gasmask ex",
	"triggers/player/gold saved",
	"triggers/player/gold spend",
	"triggers/player/has ammo",
	"triggers/player/has equipment",
	"triggers/player/has target",
	"triggers/player/heap",
	"triggers/player/holster",
	"triggers/player/in combat",
	"triggers/player/in flames",
	"triggers/player/input",
	"triggers/player/installed upgrade",
	"triggers/player/is fire",
	"triggers/player/is god mode",
	"triggers/player/is milestone",
	"triggers/player/is player busy",
	"triggers/player/jumpon",
	"triggers/player/jumpover",
	"triggers/player/ladder",
	"triggers/player/low ammo",
	"triggers/player/map",
	"triggers/player/medkit",
	"triggers/player/metal_detected",
	"triggers/player/money",
	"triggers/player/MP/assist",
	"triggers/player/MP/avenger",
	"triggers/player/MP/base_used",
	"triggers/player/MP/nemesis",
	"triggers/player/MP/payback",
	"triggers/player/MP/saviour",
	"triggers/player/nightvision",
	"triggers/player/nightvision_added",
	"triggers/player/object is close",
	"triggers/player/open backpack",
	"triggers/player/out of filters",
	"triggers/player/photo mode",
	"triggers/player/pick up ammo",
	"triggers/player/pick up fastdrop",
	"triggers/player/pick up weapon",
	"triggers/player/pick up weapon_item",
	"triggers/player/player die",
	"triggers/player/player on ai map",
	"triggers/player/pneumo",
	"triggers/player/property bit",
	"triggers/player/resource spend",
	"triggers/player/resource_spend",
	"triggers/player/revive",
	"triggers/player/sliding",
	"triggers/player/slope",
	"triggers/player/stamina",
	"triggers/player/state",
	"triggers/player/thumbstick",
	"triggers/player/torch",
	"triggers/player/visibility",
	"triggers/player/VR/gesture",
	"triggers/player/VR/mechanism pull",
	"triggers/player/weapon customize",
	"triggers/player/weapon jammed",
	"triggers/player/weapon taking",
	"triggers/player/wind orientation",
	"triggers/player/wind_orientation",
	"triggers/player_special",
	"triggers/player_vr_gesture",
	"triggers/player's state",
	"triggers/playvideo",
	"triggers/pneumo",
	"triggers/pneumo_new",
	"triggers/revive",
	"triggers/session countdown",
	"triggers/slope",
	"triggers/smell",
	"triggers/speech client",
	"triggers/speech recognized",
	"triggers/speech recognized offline",
	"triggers/start script",
	"triggers/start_script",
	"triggers/startgame",
	"triggers/stick",
	"triggers/stop script",
	"triggers/stop_script",
	"triggers/stopvideo",
	"triggers/taran",
	"triggers/throwing",
	"triggers/time_in_game",
	"triggers/torch",
	"triggers/use",
	"triggers/use multiimage",
	"triggers/use_bomb",
	"triggers/vehicles/accel",
	"triggers/vehicles/check player",
	"triggers/vehicles/check_player",
	"triggers/vehicles/hit",
	"triggers/vehicles/input",
	"triggers/vehicles/position",
	"triggers/vehicles/speed",
	"triggers/vehicles/state",
	"triggers/vehicles/suspension",
	"triggers/velocity",
	"triggers/visibility",
	"triggers/watchman group",
	"triggers/weapon down",
	"triggers/weapon jammed",
	"triggers/weapon taking",
	"triggers/weapon_active_state",
	"triggers/weapon_customize",
	"triggers/web_burn",
	"triggers/wounded",
	"triggers/xbox adaptive controller",
	"triggers/zombie",
	"triggers/zone kill",
	"triggers/zone spec/any_player_spec",
	"triggers/zone spec/generic",
	"triggers/zone spec/player_npc",
	"triggers/zone/any player",
	"triggers/zone/ctf",
	"triggers/zone/generic",
	"triggers/zone/generic-no-player",
	"triggers/zone/hq",
	"triggers/zone/kill",
	"triggers/zone/npc",
	"triggers/zone/object",
	"triggers/zone/player",
	"trolley",
	"trolley/add accel",
	"trolley/check pumping",
	"trolley/drezina debug",
	"trolley/drezina goto target",
	"trolley/drezina params",
	"trolley/driver mode hand",
	"trolley/driver mode moto",
	"trolley/kulemet mode",
	"trolley/kulemet one shot",
	"trolley/lock on target",
	"trolley/start drezina",
	"trolley/station stand mode",
	"trolley/stop drezina hand",
	
	// Arktika.1
	"actions/alt_ammo_mode",
	"actions/attach_vr",
	"actions/block_hand",
	"actions/change_phys_scene",
	"actions/citadel/achievements menu",
	"actions/citadel/check_rank",
	"actions/citadel/complete_objective",
	"actions/citadel/level_started",
	"actions/citadel/main menu",
	"actions/citadel/perks",
	"actions/citadel/perks_activate",
	"actions/citadel/perks_small",
	"actions/citadel/perks_unlock",
	"actions/citadel/select_level",
	"actions/citadel/set_achievments_last_seen",
	"actions/citadel/stats",
	"actions/citadel/store purchase",
	"actions/citadel/store",
	"actions/citadel/unlock vr mission",
	"actions/citadel/unlock_level",
	"actions/citadel/unlock_vr_mission",
	"actions/disable_teleport",
	"actions/engine/3d_arcade_score",
	"actions/engine/3d_user_coords_text",
	"actions/engine/3d_user_name_text",
	"actions/engine/VR/menu_input",
	"actions/engine/button_enabled",
	"actions/engine/counter control",
	"actions/engine/restore tpreset",
	"actions/engine/set_menu_label",
	"actions/entity/VR/alt ammo mode",
	"actions/entity/VR/holster weapon",
	"actions/entity/VR/set mechanism",
	"actions/entity/VR/set_mech_offset",
	"actions/entity/attach vr",
	"actions/entity/teleport control",
	"actions/entity/vr_cube control",
	"actions/game/update_play_stats",
	"actions/holster_weapon",
	"actions/new virtual grab",
	"actions/npc/play seq",
	"actions/player/VR/block hand",
	"actions/player/VR/disable teleportation",
	"actions/player/VR/teleport cooldown",
	"actions/player/arcade score check",
	"actions/player/arcade score commit",
	"actions/player/arcade score",
	"actions/player/arcade_score",
	"actions/player/arcade_score_check",
	"actions/player/arcade_score_commit",
	"actions/scary_face",
	"actions/set mechanism",
	"actions/set_mech_offset",
	"actions/teleport_control",
	"actions/teleport_cooldown",
	"actions/vr_cube_control",
	"actions/weapon modular/power mode",
	"actions/weapon/VR/lock target",
	"actions/weapon/VR/safelock",
	"actions/weapon/safelock",
	"actions/weapon/weapon_lock_target",
	"checker/entity/VR/can_be_holstered",
	"checker/entity/VR/is_holstered",
	"checker/player/is attached",
	"checker/pneumo/pressure",
	"checker/previous_map",
	"checker/sound_language",
	"debug/simulate_start",
	"entities/holstered_weapon",
	"entities/nearest_enemies",
	"entities/random_npc",
	"logic/xor-multi",
	"trigger/pinned",
	"triggers/block_explosion",
	"triggers/citadel/arktika mainmenu",
	"triggers/citadel/level_selected",
	"triggers/citadel/perks",
	"triggers/citadel/teleport",
	"triggers/citadel/vr_mission_trigger",
	"triggers/citadel_purchase",
	"triggers/engine/graphics_changed",
	"triggers/hand_orientation",
	"triggers/magnetic_holster",
	"triggers/menu_option_changed",
	"triggers/modular_customize",
	"triggers/store_selection",
	"triggers/turret",
	"triggers/wall_collision",
	"triggers/weapon/can fire",
	
	// added in Exodus with DLC's
	"actions/chained_humanimal",
	"actions/change_icon",
	"actions/game/set_tablet_preset",
	"actions/human/use_shooting_target",
	"actions/npc/register_motion_sensor_adv",
	"actions/player/level map mark ex",
	"actions/player/set_crosshair_style",
	"triggers/gamepad_custom",
	
	"actions/achievement hint",
	"actions/backpack craft",
	"actions/costumes craft",
	"actions/engine/apply tpreset ex",
	"actions/engine/replace tpreset ex",
	"actions/engine/set local wind",
	"actions/engine/set_local_wind",
	"actions/entity/bending tree",
	"actions/entity/bending_tree",
	"actions/entity/flock params",
	"actions/entity/ignore in pickup use",
	"actions/entity/ignore in pickup",
	"actions/game/Set Map Preset",
	"actions/game/set_save_icon",
	"actions/game/ui/change icon",
	"actions/human/use shooting target",
	"actions/map_text ex",
	"actions/monster/blind range attack",
	"actions/monster/blind_range_attack",
	"actions/monster/humanimal/chained humanimal",
	"actions/monster/stick to",
	"actions/monster/stick_to",
	"actions/npc/register motion sensor advanced",
	"actions/physics/set jumpover allowed",
	"actions/player/level map mark visibility",
	"actions/player/map text ex",
	"actions/player/set crosshair style",
	"actions/set_jumpover_allowed",
	"actions/show_achievements",
	"actions/trade/backpack craft",
	"actions/trade/costumes craft",
	"actions/ui/achievement hint",
	"actions/ui/show_achievements",
	"actions/weapon/force spinning",
	"debug/actions/input generator",
	"debug/actions/input_recording",
	"debug/text splash",
	
	"subscript/script",
	"subscript/script_block_output",
	"subscript/script_block_input",
	"subscript/script_block_reference",
	"subscript/script_cover_reference"
];

var hash_table = new Object;
for(var i = 0; i<clsids.length; i++)
	hash_table[crc32(clsids[i])] = clsids[i];