var r = reader

r.ReadHintStr("sky_texture", "choose")
r.ReadHintStr("sky_hdr_light_texture", "choose")
r.ReadVec4("sky_color", "color, vec4f")
r.ReadFP32("sky_rotation", "angle, fp32")
r.ReadHintStr("clouds_texture", "choose")
r.ReadVec4("clouds_color", "color, vec4f")
r.ReadFP32("clouds_scale")
r.ReadFP32("clouds_speed")
r.ReadFP32("fog_distance")
r.ReadVec4("fog_color", "color, vec4f")
r.ReadVec4("fog_color2", "color, vec4f")
r.ReadFP32("fog_nearplane")
r.ReadFP32("fog_skygradient")
r.ReadFP32("fog_height")
r.ReadFP32("fog_baseheight")
r.ReadFP32("fog_density")
r.ReadFP32("wind_direction", "angle, fp32")
r.ReadFP32("wind_speed")
r.ReadVec4("ambient", "color, vec4f")
r.ReadVec4("hemi_color", "color, vec4f")
r.ReadFP32("hemi_spec")
r.ReadFP32("ssr_factor")
r.ReadVec4("sun_color", "color, vec4f")
r.ReadVec2("sun_dir")
r.ReadFP32("sun_shadowrange")
r.ReadFP32("sun_scurve")
r.ReadFP32("light_lod")
r.ReadFP32("lum_scale")
r.ReadFP32("lum_ambient_lights")
r.ReadHintStr("flares2", "choose")
r.ReadVec2("flares_dir")
r.ReadBool("frares_link_to_sun")
r.ReadVec4("flares_color", "color, vec4f")
r.ReadFP32("lshafts_intensity")
r.ReadVec4("lshafts_color", "color, vec4f")
r.ReadHintStr("sun_texture", "texture, str_shared")
r.ReadVec4("sun_sprite_color", "color, vec4f")
r.ReadFP32("sun_sprite_radius")